### ISSUE TITLE
CoinJoin transactions

### ISSUE THREAD

**Issue by jonathancross** [mycelium-com/wallet-android#187]
Enhancement request: Would really love to see CoinJoin as a privacy option in Mycelium (ideally on by default).
There is even a 42 BTC [bounty](https://bitcointalk.org/index.php?topic=279249.msg2983911#msg2983911) to incentivize wallet developers: `3M8XGFBKwkf7miBzpkU3x2DoWwAVrD1mhk`

**Comment by Giszmo** [comment]
Hi @jonathancross, we are actively working on this since at least a month but it's not trivial.

**Comment by FrancisPouliot** [comment]
@Giszmo How about the option to perform a transcation which uses multiple inputs as distinct transacions (i.e. max 1 input per tx) ?

**Comment by Giszmo** [comment]
@FrancisPouliot that's merge avoidance and also important but addressed in other issues.

**Comment by Giszmo** [comment]
Merge avoidance only makes sense if the recipient provided more than one address. Also him not avoiding merges weakens the privacy.

**Comment by jonathancross** [comment]
@Giszmo Fantastic to see movement on this!

**Comment by jonathancross** [comment]
@Giszmo You might consider integrating with JoinMarket ([GitHub](https://github.com/JoinMarket-Org/joinmarket) | [bitcointalk](https://bitcointalk.org/index.php?topic=919116.0)) which would provide much greater liquidity and should be easier than starting from scratch.

**Comment by jonathancross** [comment]
Thanks @Giszmo

> ...collude "spy" on takers, to minimize costs from bad takers.

Too bad.  I'm surprised that the makers have the ability to undermine the platform's privacy in this way.

> CoinShuffle++

Great! This would rely on Mycelium servers though, correct? Can't have everything I suppose, but would be nice if there was a plan for how this could eventually be decentralized.

**Comment by Giszmo** [comment]
We plan to have no servers at some point. We need some kind of rendez-vous point but that can be solved without running one centralized server eventually.
