### ISSUE TITLE
Add EPC069-12 support to simplify sepa payments

### ISSUE THREAD

**Issue by Walkingmage** [mycelium-com/wallet-android#234]
http://www.europeanpaymentscouncil.eu/index.cfm/knowledge-bank/epc-documents/quick-response-code-guidelines-to-enable-data-capture-for-the-initiation-of-a-sepa-credit-transfer/epc069-12-quick-response-code-guidelines-to-enable-the-data-capture-for-the-initiation-of-a-sepa-credit-transferpdf/

**Comment by DanielWeigl** [comment]
We already worked on this, but cashila also needs the postal address and zip code of the recipient... sadly this isnt included in the QR code.

But we will probably at least add the option to prefill the fields with the info from the QR code

**Comment by Walkingmage** [comment]
Considering the time it usually takes for banks to do things, I wouldn't wait for the address to be added to the spec.

**Comment by Giszmo** [comment]
With Cashila removed, this is obsolete now.
