### ISSUE TITLE
Signing messages with non-ASCII characters produces invalid signatures

### ISSUE THREAD

**Issue by hubikj** [mycelium-com/wallet-android#252]
Platform: Android 5.1.1
Version: 2.7.1

Signing messages with non-ASCII characters produces invalid signatures. Example:

-----BEGIN BITCOIN SIGNED MESSAGE-----
Example of stupid characters: Příliš žluťoučký kůň úpěl ďábelské ódy
-----BEGIN BITCOIN SIGNATURE-----
Version: Bitcoin-qt (1.0)
Address: 12fBi3G5bd3bfLghmAhzqfzB9R6NDACLpi

IKcu+BblyW1qMM7CZKGUZPGXxwPa4H+bdx4jps1KITjLPTqJKpnPr5T3hD6NEsVO64gyYL42UEmkbspZRzSg3bo=
-----END BITCOIN SIGNATURE-----

**Comment by Giszmo** [comment]
Thank you for reporting. We will look into it.

**Comment by sergeylappo** [comment]
Seems fixed
