### ISSUE TITLE
'Enter Amount' screen should use local currency by default

### ISSUE THREAD

**Issue by jonathancross** [mycelium-com/wallet-android#269]
Per #184 it seems this was fixed at some point last year, but my wallet today defaults to BTC as currency rather than using my local currency.  This can cause serious issues where user is not paying attention and enters a fiat value but doesn't realize the currency is BTC.

Example: @Giszmo in #217

**Comment by DanielWeigl** [comment]
Does the fiat value show on the balance screen?

We will use the last selected currency (either from last time you entered an amount or which one you selected on the balance screen), if the wallet has a recent exchange rate available. If non is available (or too old) it defaults to the account-default currency (which is BTC for most accounts, and eg the fiat type for coinapult accounts).

So if the wallet was unable to sync with the servers, it will fall back to BTC. We might increase the timeout for what is a valid exchange rate and maybe also implement #217 to circumvent problems arising from sync errors.

**Comment by jonathancross** [comment]
> Does the fiat value show on the balance screen?

Yes: `CHF` using Bitpay as source.

> unable to sync with the servers, it will fall back to BTC

Ah, good to know.

> increase the timeout for what is a valid exchange rate

Yes, after trying several times (using tor) I now see `CHF` as default, so your timeout suggestion might be spot-on.

**Comment by Giszmo** [comment]
> unable to sync with the servers, it will fall back to BTC

I guess this is the dangerous part. If the user assumes something but gets something different the 10th time he sends money, it's easy to miss the difference.

We have to address this in our new UI.

**Comment by Giszmo** [comment]
@Rassah this is more a UI issue. Should the user get warned if the fallback kicks in? I see potential for losing money but the warning would show a lot I guess. Maybe with a "dismiss permanently" checkbox.

**Comment by Rassah** [comment]
We could just lock it to only be able to enter the value in the amount available. If it's on CHF, keep the amount to enter locked with the text saying something like "waiting for exchange data" until the user changes it to BTC themselves.

**Comment by jonathancross** [comment]
Last update here suggests that @Rassah and @Giszmo are in agreement?
Anything more needed?
