### ISSUE TITLE
“Delete Account?” prompt should print account label

### ISSUE THREAD

**Issue by fortran77** [mycelium-com/wallet-android#333]
When deletion of an acccount is requested (e.g.: Accounts tab => select account => **⋮** => Delete ...), small prompt window asks the user to confirm deletion with a Yes or No.

The account itself is listed on a dimmed background,. Depending on how many accounts exist and their placement on the screen, the account to be deleted may be completely obscured by the small window. Someday a forgetful or careless person will delete the wrong account.

It would be great if the account label itself were included within or near the prompt, e.g.: “Delete Account xxxyyy?”

**Comment by sergeylappo** [comment]
Now it's where it should be. Account name and balance are shown in "delete" and "archive" popups.
