### ISSUE TITLE
Nano Ledger S and test-net

### ISSUE THREAD

**Issue by yura-pakhuchiy** [mycelium-com/wallet-android#345]
Nano Ledger S displays incorrect destination address when Mycelium is in test-net mode. It displays main-net style adress (1...), instead of test-net one (m...). Everything else seems to work fine: amount and fee displayed correctly and transaction get signed. However, displaying main-net address may scare user away if he stores both main-net and test-net coins in the wallet.

I contacted Ledger developers regarding this issue and they proposed following fix:
> invoke SET ALTERNATE COIN VERSION (https://github.com/LedgerHQ/blue-app-btc/blob/master/src/btchip_apdu_set_alternate_coin_version.c) in your code to set the new values (APDU would be E014000005006F00C401 for Testnet)"

https://github.com/LedgerHQ/ledger-nano-s/issues/13

**Comment by Giszmo** [comment]
Can't test it here and not sure how many people are affected at all but OP sounds like it has an easy fix? Will see when to address this.

**Comment by sergeylappo** [comment]
You should install ledger testnet app (after enabling developer options)
https://www.reddit.com/r/ledgerwallet/comments/7kp0l3/ledger_nano_s_on_btc_testnet/
