### ISSUE TITLE
The discrepancy between "balance" and "spendable" amount is confusing

### ISSUE THREAD

**Issue by Giszmo** [mycelium-com/wallet-android#361]
Please explain better how the spendable amount comes to be.

With a balance of 55USD:
![img_20170601_135956](https://user-images.githubusercontent.com/96378/26899348-dab9f554-4b9c-11e7-995c-4d06945ed72e.jpg)

I don't expect my spendable amount to be 0USD:
![screenshot_2017-06-01-14-04-57](https://user-images.githubusercontent.com/96378/26899351-dedd5752-4b9c-11e7-8d9f-cc3f50dc4cec.png)

Maybe the amount widget should also allow switching the priority but as a start, there should be a details-button where the fees are explained. Some Alert showing: "Your Bitcoins are in 92 UTXOs. A transaction with 92 inputs and one output usually is 2000 bytes in size. At the selected low priority you have to pay 220sat/B. 2000B * 220sat/B = 440000sat = 4.4mBTC = 13USD. Your balance 12 USD minus 13 USD = -1USD."

Pull Requests welcome. This is probably not hard to implement.

**Comment by sergeylappo** [comment]
@Giszmo, as long as we have "How is it calculated" I suppose that we may close it?
