### ISSUE TITLE
Bump Fee (Child pays for Parent) on view-only address crash the app

### ISSUE THREAD

**Issue by anonimou0** [mycelium-com/wallet-android#362]
I've a pending transaction and tried just to see what would happen on my "view only" wallet to bump the fee.

As expected, not having the private key on the app, the replace by fee didn't work. However, instead of showing some error dialog or not even allowing me to do it, it complete crashed the application.

Probably, this was a use case not previewed.

Great app guys! Thanks!

**Comment by Giszmo** [comment]
Hi. Thank you for reporting. We have to fix it. The button should not be visible in this case.

**Comment by Giszmo** [comment]
this is fixed
