### ISSUE TITLE
Add Brazilian exchanges

### ISSUE THREAD

**Issue by sergiobenrocha2** [mycelium-com/wallet-android#369]
Hi, is it possible to add Brazilian exchanges when currency == BRL?

Right now U$ 1 = R$ 3.18 in this app, when on exchanges like Foxbit it's R$ 3.54

Some exchanges I know: Foxbit, Walltime, Mercado Bitcoin, Bitcointoyou, CoinBR

OBS: btc values (Bitstamp): R$ 7916.87; U$ 2489.03

Edit: Exchanges requested, with respective api urls:

- [x] [foxbit](https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC)
- [x] [mercado bitcoin](https://www.mercadobitcoin.net/api/ticker/)
- [x] [bitcointoyou](https://www.bitcointoyou.com/api/ticker.aspx)

**Comment by sergiobenrocha2** [comment]
Btw, from where that 3,18 came from? Commercial dollar is right now R$ 3,31.

If you want to come to a fair BRL value without local exchanges, remember Brazil has a tax called IOF (6.38%), and most credit cards charges 4% (for international purchases). The U$ price used by credit cards is dollar Ptax [1]

So U$ 1.00 = R$ 3.3076 (Ptax, 2017/06/30), with 1,0638x1,04 --> U$ 1.00 = R$ 3.66

[1] http://www4.bcb.gov.br/pec/taxas/port/ptaxnpesq.asp?id=txcotacao

**Comment by Giszmo** [comment]
You can select different exchanges. Currently there are available:

      Collections.addAll(marketWatchers,
            new BitstampMarketWatcher(new Slf4jBridge(BitstampMarketWatcher.class)),
            new QuadrigaCxMarketWatcher(new Slf4jBridge(QuadrigaCxMarketWatcher.class)),
            new BtceMarketWatcher(new Slf4jBridge(BtceMarketWatcher.class)),
            new KrakenMarketWatcher(new Slf4jBridge(KrakenMarketWatcher.class)),
            new BtcChinaMarketWatcher(new Slf4jBridge(BtcChinaMarketWatcher.class)),
            new CoinbaseMarketWatcher(new Slf4jBridge(CoinbaseMarketWatcher.class)),
            new BitPayMarketWatcher(new Slf4jBridge(BitPayMarketWatcher.class)),
            new BitcoinAverageMarketWatcher(new Slf4jBridge(BitcoinAverageMarketWatcher.class)),
            new BitfinexMarketWatcher(new Slf4jBridge(BitfinexMarketWatcher.class)),
            new AnxproMarketWatcher(new Slf4jBridge(AnxproMarketWatcher.class)),
            new CoinapultMarketWatcher(new Slf4jBridge(CoinapultMarketWatcher.class)),
            new ItBitMarketWatcher(new Slf4jBridge(ItBitMarketWatcher.class)),
            new BitcoinVenezuelaWatcher(new Slf4jBridge(BitcoinVenezuelaWatcher.class)),
            new GeminiMarketWatcher(new com.mrd.market.Slf4jBridge(GeminiMarketWatcher.class)));

(Yes, I know, this is not beautiful code.)

Adding new exchanges is rather easy and you can help with that by providing the public api. For bitstamp that's https://www.bitstamp.net/api/ticker/ for example.

The formula regarding taxes is not within the scope of this tool and of course there is no definite answer to the value of a bitcoin.

**Comment by sergiobenrocha2** [comment]
Thanks. Well, at least the app should use the right price, that 3.18 comes from nowhere.

**Comment by Giszmo** [comment]
3.18 comes from somewhere. Maybe Bitstamp. It's always USD value translated by "official" USD/BRL rate.

**Comment by sergiobenrocha2** [comment]
What "official" resource do you use to BRL? Any tip to find in the code?

**Comment by sergiobenrocha2** [comment]
I think for Foxbit is this:

https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC

**Comment by sergiobenrocha2** [comment]
Mercado Bitcoin price:

https://www.mercadobitcoin.net/api/ticker/

**Comment by sergiobenrocha2** [comment]
Bitcointoyou price:

https://www.bitcointoyou.com/api/ticker.aspx

**Comment by sergiobenrocha2** [comment]
Walltime guys are still working on the API, so I removed it from the list

**Comment by Giszmo** [comment]
I guess this issue will be a good resource for the next round of updating price feeds. Thank you.

**Comment by Giszmo** [comment]
Did some coding today. This is what a console script gives me:

````
Source: Bitstamp Units: USD/BTC URL: https://www.bitstamp.net/api/ticker/ Price: <Unknown>
Source: QuadrigaCX Units: USD/BTC URL: https://api.quadrigacx.com/v2/ticker?book=btc_usd Price: <Unknown>
Source: Kraken Units: EUR/BTC URL: https://api.kraken.com/0/public/Ticker?pair=XBTCZEUR Price: <Unknown>
Source: BTC China Units: CNY/BTC URL: https://data.btcchina.com/data/ticker Price: <Unknown>
Source: Coinbase Units: USD/BTC URL: https://coinbase.com/api/v1/prices/spot_rate Price: <Unknown>
Source: BitPay Units: USD/BTC URL: https://bitpay.com/api/rates Price: <Unknown>
Source: Bitfinex Units: USD/BTC URL: https://api.bitfinex.com/v1/ticker/btcusd Price: <Unknown>
Source: Anxpro Units: USD/BTC URL: https://anxpro.com/api/2/btcusd/money/ticker Price: <Unknown>
Source: BitcoinVenezuela.com Units: VEF/BTC URL: https://api.bitcoinvenezuela.com/ Price: <Unknown>
Source: Gemini Units: USD/BTC URL: https://api.gemini.com/v1/pubticker/btcusd Price: <Unknown>
Source: Bitcoin To You Units: BRL/BTC URL: https://www.bitcointoyou.com/api/ticker.aspx Price: <Unknown>
Source: Blinktrade Units: BRL/BTC URL: https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC Price: <Unknown>
Source: MercadoBitcoin.Net Units: BRL/BTC URL: https://www.mercadobitcoin.net/api/ticker/ Price: <Unknown>
Waiting for:Bitstamp
Waiting for:Bitstamp
Waiting for:QuadrigaCX
Waiting for:QuadrigaCX
Waiting for:BTC China
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Waiting for:Blinktrade
Source: Bitstamp Units: USD/BTC URL: https://www.bitstamp.net/api/ticker/ Price: {Source: Bitstamp time: Thu Oct 19 19:14:43 CLST 2017 currency: USD/BTC price: 5721.08}
Source: QuadrigaCX Units: USD/BTC URL: https://api.quadrigacx.com/v2/ticker?book=btc_usd Price: {Source: QuadrigaCX time: Thu Oct 19 19:14:44 CLST 2017 currency: USD/BTC price: 5875.73}
Source: Kraken Units: EUR/BTC URL: https://api.kraken.com/0/public/Ticker?pair=XBTCZEUR Price: {Source: Kraken time: Thu Oct 19 19:14:43 CLST 2017 currency: EUR/BTC price: 4815.0}
Source: BTC China Units: CNY/BTC URL: https://data.btcchina.com/data/ticker Price: {Source: BTC China time: Thu Oct 19 19:14:44 CLST 2017 currency: CNY/BTC price: 28158.0}
Source: Coinbase Units: USD/BTC URL: https://coinbase.com/api/v1/prices/spot_rate Price: {Source: Coinbase time: Thu Oct 19 19:14:43 CLST 2017 currency: USD/BTC price: 5720.0}
Source: BitPay Units: USD/BTC URL: https://bitpay.com/api/rates Price: {Source: BitPay time: Thu Oct 19 19:14:43 CLST 2017 currency: USD/BTC price: 5721.1}
Source: Bitfinex Units: USD/BTC URL: https://api.bitfinex.com/v1/ticker/btcusd Price: {Source: Bitfinex time: Thu Oct 19 19:14:43 CLST 2017 currency: USD/BTC price: 5702.1}
Source: Anxpro Units: USD/BTC URL: https://anxpro.com/api/2/btcusd/money/ticker Price: {Source: Anxpro time: Thu Oct 19 19:14:44 CLST 2017 currency: USD/BTC price: 5651.15313}
Source: BitcoinVenezuela.com Units: VEF/BTC URL: https://api.bitcoinvenezuela.com/ Price: {Source: BitcoinVenezuela.com time: Thu Oct 19 19:14:43 CLST 2017 currency: VEF/BTC price: 1.8800489823756E8}
Source: Gemini Units: USD/BTC URL: https://api.gemini.com/v1/pubticker/btcusd Price: {Source: Gemini time: Thu Oct 19 19:14:43 CLST 2017 currency: USD/BTC price: 5719.98}
Source: Bitcoin To You Units: BRL/BTC URL: https://www.bitcointoyou.com/api/ticker.aspx Price: {Source: Bitcoin To You time: Thu Oct 19 19:14:43 CLST 2017 currency: BRL/BTC price: 17308.0}
Source: Blinktrade Units: BRL/BTC URL: https://api.blinktrade.com/api/v1/BRL/ticker?crypto_currency=BTC Price: {Source: Blinktrade time: Thu Oct 19 19:14:48 CLST 2017 currency: BRL/BTC price: 17705.0}
Source: MercadoBitcoin.Net Units: BRL/BTC URL: https://www.mercadobitcoin.net/api/ticker/ Price: {Source: MercadoBitcoin.Net time: Thu Oct 19 19:14:43 CLST 2017 currency: BRL/BTC price: 17293.50038}

Process finished with exit code 0
````

**Comment by sergiobenrocha2** [comment]
Nice, it updated today, but:

Foxbit: does not appear in the exchange list
Bitcointoyou: appears in the list, but it's not working (and it's misspelled, it's "Bitcointoyou" all together)

Mercado Bitcoin is the only one working (misspelled too, just "Mercado Bitcoin")
