### ISSUE TITLE
RMC advertising 

### ISSUE THREAD

**Issue by elichai** [mycelium-com/wallet-android#381]
About the RMC advertising. I really think it shouldn't be a real part of the app, it will confuse beginners and make them buy stuff accidentally without understanding.
Please consider making it more obvious that it's not bitcoin and has nothing to do with bitcoin or the app.

Thanks,
Elichai. 

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MeniRosenfeld** [comment]
Agreed with Elichai. As I also wrote on Reddit:

This is crossing a line. I'm recommending Mycelium to all newcomers who use Android and have done so for years, and I definitely don't want them to see a link to buy some fishy ICO token at the home page.

If you must monetize, I would much rather have the app charge modest, opt-out fees for every transaction.

**Comment by Bitim** [comment]
Agreed.

**Comment by mishax1** [comment]
Thanks, Mycelium. Bye

**Comment by 5a1t** [comment]
Not happy with RMC included in Mycelium. Release a paid version that doesn't include the monetization bloat. Don't want to deal with sideloading updates.

**Comment by rebroad** [comment]
This should more clearly be shown that it's an advert not endorsed by mycelium, otherwise mycelium's reputation is being put at risk.

**Comment by Giszmo** [comment]
buy rmc button was long removed.
