### ISSUE TITLE
How do I redeem my bitcoin cash

### ISSUE THREAD

**Issue by KodeToad** [mycelium-com/wallet-android#382]
I have an account in my Mycelium wallet that had bitcoin in it on Aug1.
I want to get the bitcoin cash from it.
What can I do?

**Comment by Giszmo** [comment]
While I believe there is work being done to add a feature to the wallet, you can do this already now, thanks to the use of standards. Check [this link](https://www.reddit.com/r/mycelium/comments/6v3z3t/faq_how_do_i_send_the_bitcoin_cash_i_have_in_my/) for more details.

**Comment by rebroad** [comment]
Can this issue stay open until this feature is added?

**Comment by bom64** [comment]
You can access your bcash stored on Mycelium prvkeys before the fork using https://www.electroncash.org/

**Comment by Giszmo** [comment]
Disclaimer: Mycelium does not recommend any third party tools to claim your BCH. Keep your private keys private as much as possible. Be aware that by sharing your 12 words backup with more than one tool, bugs or troyans int more than one tool might affect all your private data associated with those private keys. The recommendation therefore is to migrate to a new masterseed before exposing the old one to a third party tool.

**Comment by sergeylappo** [comment]
Release, which supports BCH is now rolling out. 
It's not full support, but now you could exchange your BCH to BTC.

**Comment by Giszmo** [comment]
the title of this issue should be sufficiently resolved.
