### ISSUE TITLE
Recover RMC

### ISSUE THREAD

**Issue by Paddieaaa** [mycelium-com/wallet-android#395]
Hi, Could you please post here the procedure to recover RMC that was sent accidentally to a bitcoin address. In my case it was sent to my own bitcoin address in the mycelium wallet.

There might be less support tickets then if people can find the solution on the internet (while you guys have a problem with support).

Thank you!

**Comment by Paddieaaa** [comment]
Nothing?

**Comment by AroseChaos** [comment]
Same here. Please help anyone?????

**Comment by jorijnsmit** [comment]
RMC is a coloured coin and can thus be sent to BTC addresses. If the transaction has been confirmed there is no way to get them back unless you have the private key for the destination address.

Can you try making a backup of your BTC account and adding it to a new instance of Mycelium (make sure to properly backup all your accounts first!!!)? I think it might discover the coloured coins present on the address and automatically add an RMC subaccount. At least this is how backups work for RMC addresses and in essence they share the same public/private key...
