### ISSUE TITLE
Main screen doesn't show unconfirmed transactions, if those don't change the balance.

### ISSUE THREAD

**Issue by Giszmo** [mycelium-com/wallet-android#402]
If you consolidate your UTXOs with a zero fee transaction (send all funds of Account 1 to Account 1), you see no pending transaction on the main screen but in the transaction history you see it in green. See pix:

![screenshot from 2017-10-06 21-42-49](https://user-images.githubusercontent.com/96378/31303196-f8d3bf00-aadf-11e7-9efb-1f571bdfd2c7.png)
![screenshot from 2017-10-06 21-42-57](https://user-images.githubusercontent.com/96378/31303198-fb413dda-aadf-11e7-90c8-bdd402502bda.png)

**Comment by sergeylappo** [comment]
Now you can see that you spend "just a bit". Would close, please feel free  to reopen if still reproduced.
