### ISSUE TITLE
Main screen doesn't show unconfirmed transactions

### ISSUE THREAD

**Issue by bom64** [mycelium-com/wallet-android#403]
Think this bug is related to bug #402 .
https://blockchain.info/tx/b58823bf7711893ec2fef2972d08b527d7f8a7ab91fdf2cad680af066845ba49
is not displayed in Mycelium.
Normal Mycelium immediately display receiving tx, but now it is first when tx is confirmed.

**Comment by TomasJuocepis** [comment]
+1. I just started using mycelium, transferred some coins, and it's not showing up in the android app (it's unconfirmed yet).

**Comment by Giszmo** [comment]
very low fee transactions don't propagate well on the bitcoin network. There might not be much we can do about it other than to try to connect to more full nodes. When OP shared this issue, our own servers would not have relayed the 1sat/B transaction referenced. Now, 0.95sat/B are the lowest that gets relayed.

I see a necessity to see incoming transactions for CPFP for example but I see no way to ensure this happens on the bitcoin network. Maybe we need a way to import raw transactions.

**Comment by sergeylappo** [comment]
Incoming transactions are shown on balance screen before first confirmation.
Now should be fixed.
Please feel free to reopen if still reproduces.
