### ISSUE TITLE
Notification when payment is received

### ISSUE THREAD

**Issue by bjacquin** [mycelium-com/wallet-android#405]
Hi,

I was wondering if you panned to add some sort of notification when a payment is received ? This for confirmed and unconfirmed transactions.

This is a feature existing in CoPay which is very useful to have in MyCelium.

Cheers

**Comment by 5270695349848829** [comment]
Ok

**Comment by Giszmo** [comment]
#232 explains why this was never added. With modularization we will be able to provide it thuogh.
