### ISSUE TITLE
Preparing transaction while offline uses default currency (USD)

### ISSUE THREAD

**Issue by OpenGrid** [mycelium-com/wallet-android#406]
There's a bug that in effect sends amount in wrong currency than chosen while creating one. 
When you go online and mycelium sends this transaction (scheduled to send when online) it uses USD currency as a base not the chosen one. The effect is you may send different amount than you wanted because of different currency.

**Comment by Giszmo** [comment]
So you claim that if I create a transaction to send $1000 CLP ($1.3US), I end up sending $1000US?

As the fiat amount is only shown for informational purpose, while the transaction is built and finalized in BTC in the case you describe, I highly doubt this is happening. Please explain how to reproduce.
