### ISSUE TITLE
Allow Users to specify their own Bitcoin nodes they want to connect to

### ISSUE THREAD

**Issue by jmliz** [mycelium-com/wallet-android#408]

**Comment by Giszmo** [comment]
this will be part of modularization. closing this as it's not a helpful issue the way it is now. also you can already do this with testnet,

**Comment by jmliz** [comment]
@Giszmo I didn't know about the spv module. I installed a mycelium spv module from google's play store but it's only for testnet and can specify trusted nodes, that's exactly what I was asking for but for mainnet.

**Comment by Giszmo** [comment]
It's only testnet because it's still far from working smoothly.
