### ISSUE TITLE
Change "send" ux flow to prevent unspendable dust

### ISSUE THREAD

**Issue by durbanpoison** [mycelium-com/wallet-android#415]
Let me know if there's a better way to word the title of this issue.  

**Replicating the issue**  

1. Press "Send"  

2. Enter address  

3. Select mining fee  

4. Enter max amount  

5. Press "Send"  

The result can be that after Step 4, the mining fee selected in Step 3 has changed (for example due to there being more or less inputs in the transaction than the wallet previously estimated). If the user doesn't notice this change, or doesn't know how to correct the situation, then the user could be left with unspendable or uneconomic "dust" in their wallet after sending the transaction.  

**Expected result**  

After selecting the fee and choosing to send the max amount, I expect the wallet to be empty.  

**Actual result**   

Somehow my wallet is left with unspendable dust.  

**Suggested fix**  

Make the send flow multiple, sequential steps instead of cramming everything into one page where users can easily mess up the "ideal" flow.  

Page 1. Enter address  

Page 2. Select fee (measured in sat/byte)  

Page 3. Enter amount  

Page 4. Confirm amount + fee, send  

Doing it this way will make it almost impossible for users to accidentally leave unspendable dust in their wallet (they would have to choose to send an amount that is less than the max, but greater than the amount necessary to leave spendable change in their wallet).

**Comment by Giszmo** [comment]
If you take the steps above, you should end up emptying out your account, with no dust left. (Not exactly true, as you leave already unspendable UTXOs behind but you don't create new unspendable UTXOs)

The mining fee you select is in terms of sat/B, not in absolute terms, so the later steps should not break your assumptions. Problem is users, picking first the amount and then the fee and that is only problematic if max amount is used. For other amounts, having the accurate feedback on both relative and absolute fees is a desired feature.

**Comment by durbanpoison** [comment]
> (Not exactly true, as you leave already unspendable UTXOs behind but you don't create new unspendable UTXOs)  

Interesting, maybe this is what happened? However if this is the case perhaps the user should be made aware of this at some point during the transaction. There could be an "unspendable" amount included in the total, for example. Just brainstorming now. I did not expect there to be unspendable dust in the transaction that prompted this issue but it is possible.

**Comment by Giszmo** [comment]
The unspendable dust never enters the transaction. It might be left-overs from low-fee times and they might turn spendable in future low-fee times. UTXOs that are used in the transaction never produce dust UTXOs according to the presumed fee level.

**Comment by durbanpoison** [comment]
Ok I am going to close this issue unless it shows up again in the future. I will carefully watch the behavior to see if it's a bug, ux issue, or user error.
