### ISSUE TITLE
right branch for contribution ? 

### ISSUE THREAD

**Issue by hannesa2** [mycelium-com/wallet-android#416]
I work on a PR for Android O support, but I'm a little bit confused, from where to start.
Currently I branched out form 
`master` .. last commit 11.Oct, but there is a 
`develop` too ... last commit 7.Sep older ! And I see high stimulated and already Android O ready
`modularization` ... last commit 28.Oct

My question: Where is the commit from branch out to make some improvements ?

**Comment by Giszmo** [comment]
we started using these branches and the public repository for actual development commits only recently. Daniel Weigl had lumped together commits from a private repo to push them to the public repo's master branch. By using basically the same repo for both, we try to improve engagement like yours but we might still do many things wrong, so thank you for your feedback.

I guess what happened with the develop branch is that we never updated the HEAD of that branch, although we push its commits to the public repo all the time. I will do that now ... and it's looking much more active now, although I doubt I pushed any actual commits.

;develop: develop branch for the release branch master. this is what the mainnet wallet on the playstore is based on.
;modularization: develop and release branch for our modularization efforts. This is what the testnet wallet on the playstore is based on.

**Comment by Giszmo** [comment]
Version upgrades are something we usually do very carefully. Some libraries are really old. On the modularization branch I was given more freedom to break stuff, which is why I upgraded a lot there, that is not upgraded on master.

Is there an urgent need to upgrade master to Android O?

**Comment by hannesa2** [comment]
Android O : 
eg I saw a lot of outdated support libs `19.1.0` `23.3.0` `22.2.0`
for some it's a feature to have old mixed stuff there. I'm not.
I normally solve such issues immediate, because I know, I will solve it later or now. Why to wait ?
The same to Android O, why to wait ? Doing early means to not collect old stuff, which can cause issues as well. And there are a lot of other reasons ....

urgent: **no** 
To make it short and explain it with one word: **progress**

**Comment by Giszmo** [comment]
in the playstore, trust is not gained by updating those libraries. hardly anybody cares. But if stuff looks differently and arguably weird, users complain and that is what happens when I do something wrong in the upgrade, which makes it difficult to upgrade.

If you really want to upgrade all the libraries, your work is welcome on the modularization branch. We want to merge that into master soon-ish but with some heavy testing on our testnet app. I'm confident we can catch broken designs there.
