### ISSUE TITLE
branch modularization can't build

### ISSUE THREAD

**Issue by hannesa2** [mycelium-com/wallet-android#417]
When I try to build branch __modularization__ (which seams to be the recent work branch) it doesn't find `org.bitcoinj:bitcoinj-core:0.15-SNAPSHOT`

<img width="448" alt="image" src="https://user-images.githubusercontent.com/3314607/32414471-b5e4d792-c227-11e7-8925-a4c07fc23c8b.png">

From where it should come from ? Or what to do, to make it work ?

Btw, branch  `modularization` is no PR, so I ask you how is the best way to contribute with a PR to this branch or with a direct commit ?

**Comment by hannesa2** [comment]
When I switch back to `org.bitcoinj:bitcoinj-core:0.14.4` I run into missing methods etc...
<img width="537" alt="image" src="https://user-images.githubusercontent.com/3314607/32414724-953cb6ee-c22d-11e7-91d8-93348fb0764f.png">

please update branch for at least to be able to build !

**Comment by Giszmo** [comment]
Currently the modularization branch is what goes to our testnet wallet on google play. This is our modularization tech demo.

Master is what goes to our mainnet wallet.

Develop is what feeds into master. Features should merge into develop unless they are modularization related.

Bugfixes should merge directly to master.

The compile issues should be fixed if you followed the README.md of that branch that temporarily contains some unfortunate dependency.
