### ISSUE TITLE
Can't change language on app 

### ISSUE THREAD

**Issue by TLausZ** [mycelium-com/wallet-android#418]
Android.
It is installed in German. I go into settings and change it to English. Change did not take effect.

**Comment by Giszmo** [comment]
Thanks for reporting. Please share your device and app version.

**Comment by TLausZ** [comment]
Android 8.0.0, Mycelium 2.9.6 (290601).
My device is in german, so the the app installed it also in german. Would like to switch to englisch.

**Comment by TLausZ** [comment]
here is my screenrecord: https://makeagif.com/i/6Ob6sj
It^s already set on english and the app is in german.

**Comment by sergeylappo** [comment]
New Modular release which is rolling out now fixing this.
Please update and check.
