### ISSUE TITLE
Feature request: Send to more than one address

### ISSUE THREAD

**Issue by rebroad** [mycelium-com/wallet-android#421]
Currently in mycelium, if I want to send to two addresses, I have to wait for the 1st transaction to confirm before it even attempts to broadcast the 2nd transaction, whereas the ideal would be to allow both recipients to receive the funds in just one transaction - as Bitcoin-Qt and other wallets permit. Can this be implemented, please?

**Comment by Giszmo** [comment]
With RBF as proposed in #350 we could allow amending transactions with more recipients. Sending multiple transactions without waiting for confirmations already works without problems.

A UI to immediately send to more than one recipient was rejected earlier, although I can't quickly find the issue.

**Comment by Giszmo** [comment]
With RBF as proposed in #350 we could allow amending transactions with more recipients.

Sending multiple transactions without waiting for confirmations already works without problems.

A UI to immediately send to more than one recipient was rejected earlier, although I can't quickly find the issue.
