### ISSUE TITLE
testnet wallet shows 0 balance

### ISSUE THREAD

**Issue by jlopp** [mycelium-com/wallet-android#423]
I upgraded the testnet wallet on my phone and it required me to install the SPV module. After doing so, it shows my balance as 0 on the wallet screen, but under the accounts listing it shows the correct balance on the wallet. I tried restoring from backup on another phone but it shows 0 balance on both screens. Is the SPV module operational?

**Comment by Giszmo** [comment]
The spv module still has big limitations and is not close enough to being released on the mainnet wallet to have it where you found it. I meanwhile put the testnet wallet on the master branch again, so we will use the testnet wallet for more critical new features on the mainnet wallet again. If you are interested in how the spvmodule works, feel free to install our newly released [Mycelium Modularization Tech Preview (Testnet)](https://play.google.com/store/apps/details?id=com.mycelium.testnetdigitalassets) which is what the updated spv module will talk to.

Unfortunately the testnet version will require you to restore from backup as the db downgrade crashes and will not be fixed.
