### ISSUE TITLE
Czech translation is uncomplete

### ISSUE THREAD

**Issue by seberm** [mycelium-com/wallet-android#424]
Hello,
I just changed language to czech in the latest version of mycelium and I can see that there are some translations missing. It would be great if I could help you to fix these up.

Do you still use crowdin.com for translations? Can I get an invite? I tried to go to [mycelium's crowdin](https://crowdin.com/project/mycelium-bitcoin-wallet) but it seems I need a permission.

Thanks,
Ota

**Comment by Giszmo** [comment]
Crowdin is our tool but was not getting the adequate attention. Haven't tried merging updates to the app but haven't seen much activity neither. Who should I invite?

**Comment by seberm** [comment]
My username on crowdin is also "seberm". Thanks.
