### ISSUE TITLE
Add support for sending to bech32 addresses

### ISSUE THREAD

**Issue by Walter-Bishop** [mycelium-com/wallet-android#425]
[BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) ("bech32") enables native segwit transactions on the Bitcoin network. Using it will allow for smaller on-chain transactions. For bech32-addresses to gain adoption, wallet support is needed.

Please add support for sending to BIP173 addresses.

There are multiple reference implementation here: https://github.com/sipa/bech32/tree/master/ref/ (sadly none for Java).

**Comment by runn1ng** [comment]
See also https://github.com/mycelium-com/wallet-android/issues/430

**Comment by Giszmo** [comment]
bech32 is an encoding and nothing network specific. nevertheless there will be issues with wallets showing QR-codes in bech32 encoding if other wallets can't read that. It's probably "trivial" to add and it makes sense to first add it to the send feature before adding it to the receive features or in other words it makes sense to understand it before speaking it. Once all understand it, making it the default to speak makes sense.

**Comment by Giszmo** [comment]
added label security as bech32 has better error detection than Base58Check.

**Comment by mrnejc** [comment]
please enable bech32/segwit ASAP - the system needs to move ahead and sticking to legacy addresses/transactions is adding unnecessary stress to the mempool; more about it here: https ://www.reddit.com/r/bitcoin/comments/7rrb3w

... and I'm not even talking about the fact that not having segwit is unnecessarily costing users of this great wallet a lot of money in for of higher fees ...

**Comment by sergeylappo** [comment]
Sending and receiving enabled in release which rolled out to beta.
Closing issue.
