### ISSUE TITLE
fee calculation problematic

### ISSUE THREAD

**Issue by rebroad** [mycelium-com/wallet-android#426]
https://jochen-hoenicke.de/queue/#1w
![image](https://user-images.githubusercontent.com/1530283/32980525-0163162c-cca3-11e7-9d93-81b08757209a.png)

Taking a look at the above graph, it seems clear right now that for a tx to confirm within a day, that 30 Sat/B is more than sufficient, based on recent confirmations. However, sending a transaction just now recommended a significantly higher fee, and didn't even give the option for 30 Sat/B, it offered 1 Sat/B and then the next amount was 63 Sat/B. Can this be fixed to provide more granulatory, and/or use data based on recent mempool activitiy? Similar, a week ago, a transaction was recommended at 40 Sat/B, which then ended up taking almost 7 days to confirm due to the large mempool at the time - again, this should be been detectable if using mempool data at the time and a higher fee could have been recommended.

**Comment by Giszmo** [comment]
We use bitcoind's fee estimation and that considers the last week. We have no 24h target as that is not provided by bitcoind for these fee estimations neither. The highest block target - 20 blocks - or about 3h is the lowest fee option and looking at above chart there were times where 30sat/B would definitely not have gotten your transaction into a block in 3h or 24h for that matter. Neither 63sat/B would have achived that, if the transaction were submitted a week ago and as traffic can take off at any point in time, these conservative estimates remain valid even though bitcoin core povided methods for less conervative estimates.

Feel free to pick a low fee. Feel free to open a new issue regarding granularity but I personally cannot recommend anybody to generally go below the low fee estimate as getting transactions stuck is a very real problem that happens with the custom fees now. We suggest conservative fees that have a good chance of getting confirmed in the advertised time frame.
