### ISSUE TITLE
Continuity of this project

### ISSUE THREAD

**Issue by javier-tarazaga** [mycelium-com/wallet-android#427]
Hi guys! 

Thank you so much for the amazing project you guys have created. I have one question though. I can see in your website that you are planning to do this new big release with many added functionality. Was is the impact of that work on this project? 

Also many of the tooling and UI used so far is quite outdated and wanted to know if there is any plans to actually keep working on this project or not. Thanks!

**Comment by Giszmo** [comment]
This project is very much alive and will be continued in this repository. Changes are planned to be phased in instead of a new repo replacing this one.
