### ISSUE TITLE
Fee selections too flat, not enough relevant ranges during fee events.

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet-android#428]
By making a big flat part in the (normal) range it limiting the usable range when large fee events occurs.

![image](https://user-images.githubusercontent.com/388716/32997461-62f72dea-cd5e-11e7-9c71-c7e3d3bb1044.png)

Example : It's been 1 week that fee should have been in the 30 sat range and the lowest meaningful fee is at 39 sat/byte.

Also I don't see the point in having 1 sat/byte as some fixed fee, It can be no better than 0 sat/byte so it should also have the notice "Transaction might never happen"... It's extremely misleading and could incur financial losses to say that a transaction with 1sat/byte should take aproximately 3hours.

21.co fee time estimates is better, it give an estimate of 55 blocks, (and it's actually taking current mempool into consideration, not like Mycelium assuming a normal fee is 400sat/byte.)
![image](https://user-images.githubusercontent.com/388716/32997540-63022776-cd5f-11e7-88ad-0cf9fa9ff8cc.png)

**Comment by Giszmo** [comment]
oh, first time I see the chart above. A step chart would be more accurate, as your whole point is that you cannot pick from the interpolated line ;)

I hope to get it all more smooth yet but glad you are satisfied with the current result.
