### ISSUE TITLE
option for display off during QR code scan

### ISSUE THREAD

**Issue by wdbm** [mycelium-com/wallet-android#429]
Currently the display remains on while scanning a QR code of a private key. A possible defense against display-logger malware could be to have the option of scanning the QR code using the camera while not displaying the live view of the camera, and consequently the QR code.

**Comment by Giszmo** [comment]
Hi. Thank you for your concern. [This line](https://github.com/mycelium-com/wallet-android/blob/master/libs/zxing-android/src/main/java/com/google/zxing/client/android/CaptureActivity.java#L96) should already prevent screen recording. If your phone is not rooted, you should be safe. If your phone is rooted, there is nothing we can do to prevent theft.
