### ISSUE TITLE
Sending from bech address doesn't show in wallet

### ISSUE THREAD

**Issue by runn1ng** [mycelium-com/wallet-android#430]
I was sent money *from* native segwit wallet, it doesn't show in my wallet.

It's this transaction, not yet confirmed, but I don't see it in my account as unconfirmed yet

https://blockchain.info/address/1N1CaANgoHEGp7DPD7MJX9ZngN4MMiySv3

Similar to #425 but now I actually don't see money I should be seeing, which is more serious

**Comment by runn1ng** [comment]
From what reddit says, this is a feature, not a bug. It doesn't show until it's confirmed.

**Comment by Giszmo** [comment]
Well, I guess it's sort of a bug but should go under #379

**Comment by Perlover** [comment]
+1
I see same problem and it's bug not feature!
