### ISSUE TITLE
Offlinewallet Spending - BIP38 decryption does not work on second try

### ISSUE THREAD

**Issue by DanielWeigl** [mycelium-com/wallet-android#431]
- Enter `Offline Spending` -> `QR Code`
- Scan BIP38 encrypted paperwallet
- Enter wrong key
- See "Preparing key" and percentage increasing
- Get info that it is the wrong key
- Enter correct key
- Button gets disabled, "Preparing key", but no percentage counter, no further progress

**Comment by Giszmo** [comment]
This sounds like a regression but nothing you couldn't work around with some minor back and retry, right? We have to look into it. Thanks for reporting.

**Comment by sergeylappo** [comment]
Fixed
