### ISSUE TITLE
need old version of mycelium. 

### ISSUE THREAD

**Issue by bcecil123** [mycelium-com/wallet-android#435]
my many year old  version ( prolly when mycelium was invented ) only used 3 character codesand has 6 boxes one for each set of 3 characters . I have bitcoins in it i cant get out . Any ideas ????

**Comment by jonathancross** [comment]
Old [releases are available here on GitHub](https://github.com/mycelium-com/wallet-android/releases).  They go back to Jul 10, 2013: [v0.5.6](https://github.com/mycelium-com/wallet-android/releases/tag/v0.5.6).  They stopped tagging _new_ releases 2 years ago though.

**Comment by Giszmo** [comment]
The code for old releases is there of course and while there might not be tags, there are revisions called "version xyz" or "release xyz" that reflect the released states but @bcecil123 should not need nor try this.

The latest Mycelium does support the old backup. Just go to your accounts tab, hit the 🔑+ button, advanced, scan, scan the QR-Code of your backup pdf, enter the 15+1 letters. This should restore your single address account.

**Comment by bcecil123** [comment]
unfortunately i did not print a backup pdf i only have the code numbers there is no barcode to scan 


-------- Original Message --------
Subject: Re: [mycelium-com/wallet-android] need old version of mycelium.
(#435)

**Comment by johnzweng** [comment]
@bcecil123 Than you are out of luck. The PDF with the QR codes **is** the backup! The code you must enter in the boxes was just the password to decrypt the QR codes on the backup.
