### ISSUE TITLE
Changelly STEEM and SBD payment should require a unique memo field.

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet-android#436]
![image](https://user-images.githubusercontent.com/388716/33919667-e69b7e18-df87-11e7-9401-86cca027ee27.png)

There will be no way to tell who sent money for what transaction if a memo is not included, and if the transfer come from an exchange it could take a very long time to sort things out and result in lost funds.

**Comment by Giszmo** [comment]
![screenshot_2017-12-16-21-05-53](https://user-images.githubusercontent.com/96378/34075422-5928a40e-e2a5-11e7-99d0-0c09f191cc4f.png)

I hope people familiar with STEEM, know that there is something missing.

Transisto's screenshot is of the changelly site itself. Immediate action should probably be to disable STEEM, SBD and probably others. How about ZeroCoin?

**Comment by Giszmo** [comment]
Alts that require additional information were removed in one of our last releases

**Comment by Transisto** [comment]
As an investor in both Mycelium and Steem, I'd like to insist on this feature to be fixed and not have those coins ignored.

**Comment by Giszmo** [comment]
It was a hotfix to avoid people lose money. I don't prioritize features but feel free to open a new ticket about missing coins.
