### ISSUE TITLE
BTC not received using "Exchange other coins to BTC" 

### ISSUE THREAD

**Issue by marci** [mycelium-com/wallet-android#438]
I used in-app functionality to exchange my OMG tokens for BTC, it generated an address to send 10 OMG tokens to, but I did not receive BTC in exchange!

The address generated: 0x2d2fe42f5ad159f37498a8024d96f7cb97967c66

As you can see, the tokens are there. I don't have any other receipt or link I could provide as the mycelium app doesn't generate any.

**Comment by ScammedByMycelium** [comment]
I am wondering if your problem has been resolved? I am experiencing the same thing and am starting to get very upset.

**Comment by marci** [comment]
I just checked. It eventually got through. Wait for at least 24 hours.
