### ISSUE TITLE
Use Mycelium Bitcoin to buy Ripple?

### ISSUE THREAD

**Issue by Doug6388** [mycelium-com/wallet-android#439]
I want to buy ripple with mycelium wallet full of bitcoin.  Is there a simple method and can I move my ripple purchase back to mycelium wallet or do I need another mobile wallet?  I am trying to stay away from storing crypto on exchanges.  Regards, Doug  www.CoinXca.com

**Comment by Giszmo** [comment]
You can buy ripple or alpaca socks with your Bitcoins in Mycelium but for now, Mycelium is not a Ripple wallet.
