### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eladgel** [mycelium-com/wallet-android#440]
Creation Date: 23              ¤ 2013
Made With:  Mycelium Wallet 1.0.5
Backup Format: Mycelium Backup 1.0
Active Records: 1
Archived Records: 0
Total Keys: 1
Total Addresses: 1

my cousin have used mycelium v1.0.5 back in the day(2013) to create his wallet
We have the qr code with both the private and the public key
how can I (and if i can at all cause there are 26^15) decrypt the combination of the caps letters that I can use?

**Comment by Giszmo** [comment]
Brute forcing the missing 15 letters of an encrypted private key backup is (currently) not possible. It was a design consideration to make the pdf safe to be transferred via unsafe channels.

**Comment by 2014wallets** [comment]
I have the 15-character password, the checksum character, and the Encrypted Private Key.
How can a decrypt my private key?

**Comment by Giszmo** [comment]
If you scan an encrypted private key with Mycelium Android, it should automatically assume cold wallet spending and ask you for the password.

You can also import the account if you want Mycelium to hold on to the private key after you did your transactions/balance checking.
