### ISSUE TITLE
6 digit PIN

### ISSUE THREAD

**Issue by PotatoSalads** [mycelium-com/wallet-android#443]
I am attempting to recover my mycelium wallet. I lost the 12 word seed backup and can't remember my pin. My phone is rooted but can't find the file with the pin information. Is there anyway to recover my pin so I can access my BTC?

**Comment by Giszmo** [comment]
We urge you not to use the wallet on a rooted phone.

If you manage to do the equivalent of:

      getSharedPreferences("settings", MODE_PRIVATE).edit().putString("PIN", "").commit();

you remove the pin.
