### ISSUE TITLE
Cannot create Coinapult account

### ISSUE THREAD

**Issue by ahtaha1** [mycelium-com/wallet-android#449]
Hi, 
I have a Coinapult account which I'm trying to link to Mycelium app with no luck. Each time I tap on Add account and choose "Add Coinapult Locks Account" then tap on USD Account I get a pop up prompting for creating a new Coinapult account. When I tap "I agree" I get another popup saying "Creating Coinapult Account ..." then it fails with an error message saying "Unable to create Coinapult account" 

I tried everything with no success.

**Comment by sergeylappo** [comment]
@ahtaha1, sorry for delay and thanks for reporting. This is a known bug and fix would be released in near future. Please stay tuned.

**Comment by Giszmo** [comment]
The code was merged in our BCH support feature branch/modularization demo. Release is scheduled for this week.

**Comment by sergeylappo** [comment]
Release is rolling out.
As soon as modular update would reach you coinapult would work.
