### ISSUE TITLE
Question: how to speed up build time ?

### ISSUE THREAD

**Issue by Neustart** [mycelium-com/wallet-android#450]
Hi there !
Thanks for you wallet. Not sure that this is correct place to ask such questions, so sorry if any :)
I am trying to working with Activities code so I don't need to rebuild whole solution. 
How can I rebuild just one project ? Seems like now each time when I press "Build" It is trying to rebuild whole project, because this really taking a lot of time (~2 minutes on my PC)
Could somebody advice something ? Probably comment something for avoid such long build.
Thanks !

**Comment by Giszmo** [comment]
On latest Android Studio it takes more like 5s to deploy tiny changes to the emulator. Not doing anything special. release builds with tests and cleaning are slower.
