### ISSUE TITLE
Requesting for Filipino Laguage Translation

### ISSUE THREAD

**Issue by rfece143** [mycelium-com/wallet-android#452]
Good day!

Hi I am a filipino born citizen, I would like to ask permission from your good office to allow me to contribute in your project to translate it in filipino language. This intention of mine is to spread and help this project to be known in the philippines so that my fellow country men can use this project.

Sincerely Yours,
Roel

**Comment by Giszmo** [comment]
Hi Roel, translations are done on [crowdin](https://crowdin.com/project/mycelium-bitcoin-wallet). We haven't synced strings in a long time, busy on major new features.
