### ISSUE TITLE
TestNet stop works ?

### ISSUE THREAD

**Issue by Neustart** [mycelium-com/wallet-android#453]
Hi there,
I can't send transactions via a testnet network from the clear mycelium build.
Wapi returning success code but testnet doesn't know anything about this transaction.

![photo_2018-02-19_01-46-20](https://user-images.githubusercontent.com/10336022/36358494-fcf09d72-1517-11e8-9983-8716fcb22c57.jpg)

**Comment by sergeylappo** [comment]
@Neustart, please re sync account and try again. 
Please let me know if it works now.

**Comment by Neustart** [comment]
@sergeylappo I tied this a few times, the same result
I also tired remove an app and reinstall clean build from you github repo with a new wallet - the same result..

**Comment by sergeylappo** [comment]
@Neustart, please try to increase fee.

**Comment by sergeylappo** [comment]
@Neustart, is your issue solved?

**Comment by sergeylappo** [comment]
Neustart Closing issue, assuming resolved. If not, feel free to re-open/comment again.
