### ISSUE TITLE
Transfer BTC from a watch only account

### ISSUE THREAD

**Issue by DavidSunflower13** [mycelium-com/wallet-android#454]
As the title suggests, I'm looking for information on how to transfer Bitcoin from a watch only account. I didn't realize I copied just account when I brought in the Bitcoin initially. I've entered the master seed and still been unable to transfer my BTC. Does anyone have any recommendations or suggestions

**Comment by sergeylappo** [comment]
Please try to remove watch only account and add account from mater seed. 
Or if you are sure you want to transfer money from this account you can use "cold storage". Menu->cold storage->master seed

**Comment by sergeylappo** [comment]
@DavidSunflower13, is your issue solved?

**Comment by sergeylappo** [comment]
Closing issue, assuming resolved. If not, feel free to re-open/comment again.

**Comment by sergeylappo** [comment]
Closing issue, assuming resolved. If not, feel free to re-open/comment again.
--
