### ISSUE TITLE
How to claim my BCH from a Mycellium 1.1 Backup with 15 +1 character password paper-wallet.

### ISSUE THREAD

**Issue by SY-MEDIA** [mycelium-com/wallet-android#456]
I have a paper Mycellium encrypted Wallet Backup holding 13 records and using a 16 character ( five groups of three plus one character) password. I can't find any way to import the wallets to claim forked coins. I'm trying to extract the private key so I can claim my BCH on that wallet. Can you please direct me to instructions that would work to import that paper wallet into a BCH wallet?

**Comment by sergeylappo** [comment]
You can import it by going to accounts->advanced->scan.

**Comment by SY-MEDIA** [comment]
So Mycellium can also manage BCH Bitcoin Cash wallets??

**Comment by Giszmo** [comment]
Not yet

**Comment by sergeylappo** [comment]
Now, BCH support update is rolling out and you could exchange you BCH to BTC.
Full support would be implemented later.
