### ISSUE TITLE
Can't build the project!

### ISSUE THREAD

**Issue by rraallvv** [mycelium-com/wallet-android#458]
I tried to build the project from the root folder after cloning the repository, but the build failed with the error below. Also I'm getting lots of deprecation warnings.

```
> Task :mbw:lint
Ran lint on variant devprodDebug: 1038 issues found
Ran lint on variant prodnetRelease: 1038 issues found
Ran lint on variant devprodRelease: 1038 issues found
Ran lint on variant devRelease: 1038 issues found
Ran lint on variant btctestnetRelease: 1037 issues found
Ran lint on variant devDebug: 1038 issues found
Ran lint on variant btctestnetDebug: 1037 issues found
Ran lint on variant prodnetDebug: 1038 issues found
Wrote HTML report to file:///Users/user/Desktop/wallet-android/mbw/build/reports/lint-results.html
Wrote XML report to file:///Users/user/Desktop/wallet-android/mbw/build/reports/lint-results.xml

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mbw:lint'.
```

**Comment by rraallvv** [comment]
Excluding lint did the trick like so `./gradlew build -x lint`

**Comment by Giszmo** [comment]
You probably want to build mbw? Try `./gradlew clean test :mbw:assembleBtctestnetDebug` or whatever target you want to build.

**Comment by Giszmo** [comment]
This is documented on our current develop branch. Sorry for the mess. As all work is going into the feature-bch-exchange branch, it turned into our develop branch and unrelated stuff ended up there, too. https://github.com/mycelium-com/wallet-android/blob/feature-bch-exchange/README.md
