### ISSUE TITLE
Sent BCH from Coinbase to BTC address in mycelium

### ISSUE THREAD

**Issue by tkalfigo** [mycelium-com/wallet-android#459]
As title says, I transferred BCH (BitCoin Cash) from my Coinbase account to the BTC (Bitcoin) address of mycelium on my Android phone. The transaction is no longer pending (2h ago and 9 confirmations later) but the funds obviously not visible in BTC address.

I'm reading several similar cases online since the BCH and BTC addresses are indistinguishable from one another. Is there any action I can take to recover the funds?

**Comment by sergeylappo** [comment]
Seems resolved.
If you'll have any additional questions please feel free to open new issue, or reopen this.

**Comment by tkalfigo** [comment]
My only question is: what does the mycelium bitcoin cash module actually do? And is there a know date when mycelium will have support for Bitcoin cash?

**Comment by sergeylappo** [comment]
@tkalfigo, sorry BCH functionality is still not rolled out. 
As soon as it would be rolled out it would allow you to exchange your BCH to BTC.
