### ISSUE TITLE
how is this posible. ?stolen coin from mycelium.

### ISSUE THREAD

**Issue by lokieluke** [mycelium-com/wallet-android#472]
![screenshot_20180629-122654](https://user-images.githubusercontent.com/40679833/42070007-ef4ec43c-7b97-11e8-92ce-86a33b527af6.jpg)
![screenshot_20180629-122714](https://user-images.githubusercontent.com/40679833/42070015-f874e910-7b97-11e8-9f17-095582a8dbee.jpg)

**Comment by lokieluke** [comment]
please look closely at the 3 X 0 BTC RECEVIED 
and then when ive sent coin there are duplicate payments however the address were differen 
wtf.
please explain where and how i was robbed.

**Comment by lokieluke** [comment]
![screenshot_20180629-143423](https://user-images.githubusercontent.com/40679833/42073387-b3aa434a-7ba9-11e8-8023-2fa55416668f.jpg)
![screenshot_20180629-143427](https://user-images.githubusercontent.com/40679833/42073393-bd1c8802-7ba9-11e8-90c9-0a35860b47b4.jpg)

**Comment by lokieluke** [comment]
Now this is really bizarre I've just reloaded the blockchain and zeros have gone however if you look closely at the sent Bitcoin there's clearly 3 duplicates that are all sent to separate addresses only one of which was the address that I was originally sending it to please explain again WTF come on devs. wats the story?

**Comment by Giszmo** [comment]
Sorry but from the screenshot we cannot tell anything. Did you try to pay something and the merchant convinced you to "try again cause it failed"? Did somebody else have access to your phone? Does the merchant maybe even have a register of these extra payments? If a payment processor such as bitpay or coinbase was involved, please ask them if they know these receiving addresses. At this point I doubt it is a bug in our software.

Generally, please contact support@mycelium.com for such support requests.

**Comment by lokieluke** [comment]
hi thanks for your response.
ok so when i made transfers some how there were extra transfers made at exsactly the same time for exsactly the same amount without my knowldge and to completley different addresess.
no body had acess to my device or wallet and  keep in mind the duplicate payments were done at the same time as the original payment i was making.

i would really apreciate some help in understanding how this occoured. .
thanks from Luke
________________________________
