### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Cypherock** [mycelium-com/wallet-android#473]
Build failing with submodules not building, bitcoin cash as an example.

`Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mycelium-com/bitcoincashj.git' into submodule path 'bitcoincashj' failed
rohanagarwal94@rohanagarwal94:~/Desktop/AndroidStudioProjects/wallet-android$ sudo git submodule update --init --recursive
Cloning into 'bitcoincashj'...
Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by sergeylappo** [comment]
User banned, closing.
Most probably solution is second comment here:
https://github.com/jakubroztocil/cloudtunes/issues/23
