### ISSUE TITLE
Trezor T - import accounts - crash every time

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet-android#475]
If i try to add accounts of Trezor T - i get crash

To reproduce:

1. Tab "Accounts" -> "+" (right up corner) -> Advanced button -> Trezor button
2. Then connect Trezor T -> enter there PIN -> Host button in Trezor T (passphrase enabled there)
3. After i see password dialog in Mycelium
4. I enter there any passphrase
5. Crash

Tested in Galaxy S8 and Galaxy Tab S3

I sent report from Android but i don't hope that crash will be viewed (i did it many times and nothing result in Mycelium updates) 

Please for @slush0 too ;)

**Comment by slush0** [comment]
Generally, Trezor now sends PassphraseStateRequest message and expects PassphraseStateAck response on it.

Messages are defined here: https://github.com/trezor/trezor-common/blob/master/protob/messages-common.proto#L120

The reasoning of this change is that host is informed about device state change even when the passphrase entry has been done on-device. In Mycelium case, just ignoring the state and answering with empty PassphraseStateAck() is enough, as implemented here: https://github.com/trezor/python-trezor/blob/master/trezorlib/client.py#L420

**Comment by mycelium-cto** [comment]
Hello, @slush0. Could you ping me via cto@mycelium.com?

**Comment by sergeylappo** [comment]
Fixed in SegWit release, rolled out to users.
Closing.
