### ISSUE TITLE
enable FLAG_SECURE by default & option to override

### ISSUE THREAD

**Issue by maltfield** [mycelium-com/wallet-android#486]
This is a feature/security improvement request: please create an option for the user to toggle the FLAG_SECURE option in the mycelium bitcoin wallet android app, similar to the implementation in Signal.

   * https://github.com/signalapp/Signal-Android/issues/788

FLAG_SECURE should be on by default, and the option to toggle it off should be opt-in.

**Comment by Giszmo** [comment]
You say this would be a security improvement but as we prevent screenshots of xpriv already for example, I don't see the security improvement of optionally not preventing screenshots?

**Comment by Giszmo** [comment]
This is a duplicate of #471
