### ISSUE TITLE
Mycelium Android no server connection

### ISSUE THREAD

**Issue by kevintenda** [mycelium-com/wallet-android#489]
After the last update, when I try to go to the app from my phone I got the "no server connection" message.

I checked the connection logs and it says:

Pong! JsonRPCResponse{jsonrpc=2.0, id=13, response=null}

Starting sync: SyncMode{NORMAL_SYNC,  onlyActiveAccount ignoreSyncInterval}
Server connection failed with ERROR_CODE_NO_SERVER_CONNECTION
RpcError(code=1, message='the transaction was rejected by network rules

Then I see the Missing Inputs with a long serial number

How to solve the problem?

**Comment by kevintenda** [comment]
Well, last time I used Mycelium was last December. After that I received an update (2.12.0.17) and since then I had problems with the connection "no server connection". The thing is only mycelium gives me this problem. All the other apps connect to the server. 

Now with the newest update (2.12.0.18) I've got a new message: "A transaction failed to broadcast permanently. You can keep the transaction for further investigations or delete it. Do you want to delete failed transaction now?  YES or no"

I wonder what transaction isit talking about if all transaction I made went well?

I try to delete this app now and installing it again. If the problem persist then some mycelium devs should sort this out.

Thanks

**Comment by kevintenda** [comment]
After I delete and reinstall the app the problem disappeared.

**Comment by xkawn916** [comment]
I'm having the same problem. As soon as I start mycelium on my android I get " no server connection". Just started happening. On both of my phones. Tried restarting, tried uninstalling and reinstalling. Neither worked.

**Comment by razechlorine** [comment]
I have the same problem when i start the app it says no connection to the server, im worried to lose bitcoin

**Comment by razechlorine** [comment]
> I'm having the same problem. As soon as I start mycelium on my android I get " no server connection". Just started happening. On both of my phones. Tried restarting, tried uninstalling and reinstalling. Neither worked.

Same problem plz let me Knox if you Find sulution

**Comment by reddawg7701** [comment]
this seems to be a problem with everyone, i have the same problem and i have btc just sitting there. i deposited it there to move it to my bitpay. but now it is stuck.. where are the Mycelium devs at? why are they not answering any of us here? where is @Giszmo at?

we need some answers or awareness? hell unplug your servers and plug them back in for all i care lol

**Comment by razechlorine** [comment]
Who is @gizmo?
He a mycelium woeker?

**Comment by razechlorine** [comment]
Worker*

**Comment by reddawg7701** [comment]
Yes.. but it seems they fixed the issue. Mine started working this morning

**Comment by razechlorine** [comment]
I still have no connection to the server how can i fix this issue ? 
I already dus thé update

**Comment by reddawg7701** [comment]
I received a message from them and they said update to the new version.

I uninstalled my app and then reinstalled it using my back up

**Comment by Giszmo** [comment]
Could you please all confirm that you are running Mycelium on old Android phones? Android 4.4 (Kitkat) does not support the encryption standards devops upgraded the server to. We found out about his only recently and devops added one server now that will serve the 4.4 users. This should fix the issue.

**Comment by Giszmo** [comment]
@razechlorine please provide more information. Is your phone Android 4.4? Did you try different networks?

**Comment by reddawg7701** [comment]
I have a Google pixel that's 2 years old. Mycelium started working again
yesterday, but I'm still very concerned and skidish
