### ISSUE TITLE
Pressed refresh, and my balance went from >0 to 0 BTC.  

### ISSUE THREAD

**Issue by WordenPond** [mycelium-com/wallet-android#490]
No transactions.  I have used this wallet for years.  This was a pre-segwit wallet.  I tried to restore on another device with no luck, the balance still says zero.  Please help.  Starting to panic.  I have the 12 word phrase, and I restored it on another device.  I have the passcode too.  How can I tell if my wallet was hacked?

**Comment by MadMann** [comment]
How you try to restore your wallet (PrivateKey or Backup from App) and also what balance you seen @ https://www.blockchain.com/btc/address/

Right one or again 0 btc

**Comment by WordenPond** [comment]
Phone software update.  2 hard resets, everthing is okay now.  The balance
showing 0 and no transactions indicated it was having a hard time loading
the wallet.

**Comment by WordenPond** [comment]
Interesting.  I have between 150 - 175 transactions on the wallet. I had
done an Android system update, and had to hard reboot several times.  When
the Samsung Galaxy 7 did finally come back the first time, it showed only
the last two transactions.  That's when I knew the wallet wasn't swept, and
it was just trying to load the TXs.  I think there was an issue just trying
to contact the server to get the transaction IDs back.  A warning would be
helpful if the time taken is over a certain time.

**Comment by Giszmo** [comment]
@WordenPond this is an interesting input as all but the most recent transactions missing is contrary to what we guessed might be the case: "new, unconfirmed transactions not having propagated to a server".

As the cases I saw in screenshots had 10tx missing, I kind of guessed that it's not about some very recent transactions only but you clearly talk about confirmed transactions, right?

**Comment by WordenPond** [comment]
Correct.  It showed the last 2 Confirmed Transactions, but stopped after
that.  It must be a server error.  Is there a timeout on the response?

**Comment by Giszmo** [comment]
DevOps might have fixed the server issue. Please report if the issue persists.

**Comment by WordenPond** [comment]
Agreed.  Closed.  Will file new bug report if it occurs again and will site
#490.
