### ISSUE TITLE
The change type in options (bech32 or private) is reseted every time after restart

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet-android#493]
Hello, 

The change type in options (bech32 or private) is reseted every time after restart of Mycelium to "privacy". 

Reproduce:

1. In settings to set change type as bech32
2. To close application through Android task manager
3. Run again: in settings will be type as "Privacy guard"

Version: 2.12.0.18

**Comment by Giszmo** [comment]
thanks for reporting. can confirm the error. will fix it soon. Next release probably not yet.

**Comment by Perlover** [comment]
v2.12.0.20 - i checked right now - bug exists there. Is it normal?

**Comment by agneslovelace** [comment]
yes, not in v2.12.0.20 yet, sorry
the fix will be in v2.12.0.21
