### ISSUE TITLE
Mycelium crashes when receiving message from localtrader

### ISSUE THREAD

**Issue by 1989gironimo** [mycelium-com/wallet-android#495]
Using the latest version of Mycelium on 2019 january 24 on LineageOS 15.1 with root enabled and Tor.
Every time, the local traders tries to receive a message the crash dialog of Android appears telling me, that the app Mycelium has to be closed unfortunately.

How can I provide meaningful information to get this issue fixed?

**Comment by Giszmo** [comment]
We know about the issue and are working on it.
