### ISSUE TITLE
KeepKey WebUsb support

### ISSUE THREAD

**Issue by keepkeyjon** [mycelium-com/wallet-android#497]
https://github.com/mycelium-com/wallet-android/blob/488889f201f2d11a5eb99fb9f18a5523f6e6e894/trezor/src/main/java/com/satoshilabs/trezor/lib/KeepKey.java#L7

FYI, we're in the (slow) process of switching over to WebUsb. With that change, we had to bump the USB `productId` to `0x0002`. You can try out the new firmware via our beta client, or download the raw firmware binary on github https://github.com/keepkey/keepkey-firmware/releases/tag/v6.0.1 & upload it using one of the command-line clients.

**Comment by Giszmo** [comment]
So you are saying that Mycelium will not work with updated KeepKeys? And considering 0x1 and 0x2 there should fix this? Or did you change the api in more ways relevant to Mycelium?

**Comment by keepkeyjon** [comment]
If my reading of the code is correct, and Myclium works with a Trezor T, I think you need only add the new VID/PID pair. The interface at the message level stays the same.

Java must have nicer interfaces for communicating over usb than what we found in Javascript (node.hid / chrome.hid / chrome.usb / navigator.usb all have slightly different interfaces).

**Comment by keepkeyjon** [comment]
Looks like a patch to address this was added in https://github.com/mycelium-com/wallet-android/commit/995287b8e72711d3074cb0a4a32ce9a0e89edff4.

**Comment by Giszmo** [comment]
This issue should be resolved.
