### ISSUE TITLE
1500 dollars of bitcoin vanished.

### ISSUE THREAD

**Issue by dutenheifer84** [mycelium-com/wallet-android#500]
Have no idea what to do or where to go. I was directed to this website. I put too low of a miner fee on a transaction and after several hours decided to try to cancel the transaction and that was a month ago. I have sent email after email to support which I am convinced no longer exists. Any ideas?

**Comment by Giszmo** [comment]
Our support does exist and should answer under support@mycelium.com
Try reloading your account. The way you described using your wallet should not be dangerous to your coins. Either the intended recipient received the coins or you should still have them.

**Comment by dutenheifer84** [comment]
Well,  it was 1700. I apologize for the email as I was getting frustrated.
Took a month for support to get back to me. It has already been fixed
though and I have changed my rating back to five stars at the play store.

**Comment by pontanothai** [comment]
473135987
