### ISSUE TITLE
Incorrect Transaction Details Displayed

### ISSUE THREAD

**Issue by EAWF** [mycelium-com/wallet-android#503]
v2.12.0.26 on Android.
I have multiple existing and confirmed transactions in Bitcoin HD wallet accounts.
When I select ANY of the transactions and select "show details," The Transaction Details Screen reports valid data for the Hash, Date, Inputs, Outputs, and Miner fee, BUT:
Confirmed is displayed as "NO"
AND
Confirmations: Not quite sure where this number is coming from, but it's not the block number, and does not match the number of confirmations displayed from selecting the hash link to the block explorer. I get the same results no matter which block explorer I select and re-display the Transaction Details screen.

*NOTE: Just tested out adding a SA account from an old paper legacy wallet. Confirmed shows transactions as "In Block (correct block number)" and Confirmations show the same problem as related above.

**Comment by Giszmo** [comment]
Thank you for reporting the bug. Can reproduce it but by far not on all accounts and on affected accounts not on all transactions. We have to fix it.

**Comment by EAWF** [comment]
Changed block explorer away from blockchain.info to blockExplorer and problem resolved itself. Probably something in the output from blockchain.info changed? Still needs to be fixed, so I won't close this issue.

**Comment by EAWF** [comment]
Resolved.
