### ISSUE TITLE
I need help recover an old mycelium database from 2015

### ISSUE THREAD

**Issue by dummys** [mycelium-com/wallet-android#511]
Hello,

I have a problem with an old phone, the phone was dead and back in the days I was using mycelium and forget to backup and do the usual stuff ( remember that btc was worth nothing). I found the flahs and dumped it and now I have the "com.mycelium.wallet folder with the wakketbacking.db and "kv" data.
Did you have a tool to recover my private key ? I try to install a very old version of celium and drop all the files I recovered but the app is crashing.
Thanks for help.

**Comment by dummys** [comment]
hello ?

**Comment by dummys** [comment]
I managed to recover the Master seed of one account, but didn't find how to recover other account, please help

**Comment by dummys** [comment]
everything recovered

**Comment by RickDeckcard** [comment]
I would like more information. I am trying recovered the keys from the database but i have a little information, the databases are corrupted.
