### ISSUE TITLE
Right-to-left for Hebrew messes up the interface

### ISSUE THREAD

**Issue by shesek** [mycelium-com/wallet-android#515]
The main balance tab looks like that:

![signal-attachment-2019-07-14-131418](https://user-images.githubusercontent.com/877904/61182283-be720180-a639-11e9-9635-ca7f30391248.jpeg)

This also effects some of the other screens.

**Comment by sha-265** [comment]
Confirmed.

**Comment by Giszmo** [comment]
Thanks for reporting. We will look into this. For the meantime, please go to the app's settings and pick English as language. That overrides the system wide language setting.

**Comment by shesek** [comment]
This fixed quite a few of the issues, including the main page. The settings page still looks a bit off, but its much better than before. Thanks!

**Comment by Hitgub01** [comment]
Done

**Comment by Hitgub01** [comment]
DoneOp 16 dec. 2019 03:43 schreef Leo Wandersleb <notifications@github.com>:Closed #515.
