### ISSUE TITLE
Add SAT as an additional Denomination

### ISSUE THREAD

**Issue by frennkie** [mycelium-com/wallet-android#520]
It would be useful to also provide Satoshi as a selectable Denomination. Currently only these options are available:

 ```
    UNIT(0, "", ""),
    MILLI(3, "m", "m"),
    MICRO(6, "u", "\u00B5"),
    BITS(6, "bits", "bits");
```

**Comment by Giszmo** [comment]
The minumum amount that can be sent on-chain is hundreds of sats and so are the fees. We will add sats once we have lightning integrated.
