### ISSUE TITLE
 problem with wallet recovery

### ISSUE THREAD

**Issue by prophet666524** [mycelium-com/wallet-android#525]
guys i have a problem with recovering my wallet! I have not used it for a long time, so I decided to restore
I have : Encrypted Private Key  and 15-character password 
when I try to recover it says that the password is not correct!
but he is my correct password !!! since I restored once already with this data, what should I do ??? how do i get my BTC

**Comment by blotterandbars** [comment]
I'm in same page

**Comment by Giszmo** [comment]
We had a bug that should be fixed in 3.2.0.17 which is rolling out as soon as Google approves the release or whatever they do that delays releases some 4 to 5 days after we upload them. Please open a new issue if the problem persists on 3.2.0.17
