### ISSUE TITLE
Media Flow pushing unwanted notifications to my phone even when settings is off

### ISSUE THREAD

**Issue by ioogithub** [mycelium-com/wallet-android#527]
I am getting media flow notifications even though I have the setting turned off under Settings-> Notifications->Show Media Flow notification.

Please fix this, I really don't want Mycellium spamming my phone with this unwanted content.

I am using version 3.2.0.8

**Comment by ioogithub** [comment]
I can confirm this is still happening after upgrading to version 3.2.0.11. Every morning Mycellium is spamming my phone with ads to my notifications. I definitely have "Show Media Flow notification" turned off.

Also, I noticed that if I enter the settings and then press back, it always returns to the media flow screen by default which is also undesirable behaviour.

Is mycellium turning away from a bitcoin wallet and into an ad delivery app?

**Comment by Giszmo** [comment]
3.2.0.17 will resolve this. The version is on google play awaiting approval since three days.

**Comment by Hitgub01** [comment]
Working on itOp 16 dec. 2019 03:52 schreef Leo Wandersleb <notifications@github.com>:Closed #527.

**Comment by catskul** [comment]
Appears to still be happening even in 2022
