### ISSUE TITLE
Sync in progress: 0 transactions retrieved

### ISSUE THREAD

**Issue by ioogithub** [mycelium-com/wallet-android#530]
The app is stuck trying to sync. It never finishes.

The app is stuck trying to sync. It never finishes. Killing it and opening it again, it returns to the "Syncing in progress" it seems to be totally nonfunctional in this state.

Is there anyway to recover from this?

Update: It has been 3 hours and I am still Syncing.

**Comment by Giszmo** [comment]
This was a server issue and should be resolved.

**Comment by rene78** [comment]
Problem is back.
