### ISSUE TITLE
Backup of externally imported address cannot be verified

### ISSUE THREAD

**Issue by jbrepogmailcom** [mycelium-com/wallet-android#531]
I backed up external address, that I imported earlier. After verification, I get message that no bitcoin address has been found. I am still getting annoying message that my backup has not been verified. How to get rid off of the message? Thanks

**Comment by Giszmo** [comment]
Can you please provide more details? So you restored a wallet from the 12 word mnemonic and it still asks you to create a backup?

**Comment by jbrepogmailcom** [comment]
No. I backed up extrenal SA address that I imported. When I want to verify backup I get message that no address has been found. Apparently backup verification only works for HD addresses

**Comment by Giszmo** [comment]
The BIP38 encrypted backup decryption was broken and did just not run. If the issue persists on 3.2.17, let me know.

**Comment by Giszmo** [comment]
3.2.0.17 I meant. It should be available now.
