### ISSUE TITLE
BIP38 encrypted private key import not working

### ISSUE THREAD

**Issue by HardCorePawn** [mycelium-com/wallet-android#532]
**Steps to reproduce:**
Ensure you have a BIP38 encrypted private key on the "clipboard"

Within Mycelium, do the following:
- "Add New Account"
- Click "Advanced"
- Click "Clipboard"

"Private Key Decryption" prompt comes up

- Enter password
- Click "Decrypt"

**Expected Result:**
- Private key should be decrypted and added to wallet

**Actual Result:**
- "Preparing decryption key..." is displayed, but nothing else happens. 

Test BIP38 Key: 6PYRENAATjjPu5HPAaQ1uuF4CV8t3d32fGbjUg9DkxXnZdTuu7J3SyPN8c
Test Password: password123

Test Address: 1Jx7smpvZDqNQefTQgnJL5XREUAcqPic1d
Test WIF Key: KzaqBmUcRpFZNFtJuYK6oNENHVywrJpowYGFkk7qgNpGgVP6xs6r

Mycelium version: 3.2.0.11
Device: Nokia 7 Plus, Android 9

**Comment by HardCorePawn** [comment]
NOTE: doesn't work when scanning a QR Code of the following text either:
"bitcoin:6PYRENAATjjPu5HPAaQ1uuF4CV8t3d32fGbjUg9DkxXnZdTuu7J3SyPN8c"

Android prompts to launch Mycelium. Mycelium launches and goes to the enter password screen, but again it just sits at "preparing decryption key..." after you enter the password and click "Decrypt"

**Comment by Giszmo** [comment]
We had a bug that should be fixed in 3.2.0.17 which is rolling out as soon as Google approves the release or whatever they do that delays releases some 4 to 5 days after we upload them. Please open a new issue if the problem persists on 3.2.0.17

**Comment by reddawg7701** [comment]
this seems to be a problem with everyone, i have the same problem and i have btc just sitting there. i deposited it there to move it to my bitpay. but now it is stuck.. where are the Mycelium devs at? why are they not answering any of us here? where is @Giszmo at?

we need some answers or awareness? hell unplugg your servers and plug them back in for all i care lol
