### ISSUE TITLE
MyCelium Wallet backup issue

### ISSUE THREAD

**Issue by crowdynasty** [mycelium-com/wallet-android#534]
My problem began about nine months ago when my Android Mycelium wallet crashes while in the process of authorizing with a Trezor. This problem has reoccurred every time I attempted to send my coins. Just today I noticed there was an update released which I have not yet installed. Does anyone know if this latest update will solve my problem. I'd like to add that I used the wallet with Trezor successfully for several months with no issues so I'm curious as to the sudden failure of the APP.

Follow-up question;
I wanted to backup the wallet before updating. The APP sent a PDF in an email and I have the random password to go with it. When I open the PDF file there is no QR code displayed. I go to verify the "backup" as being successful and have no code to scan. I have tried several different programs to open the PDF file and they all show the same thing on my display.

What have I not done correctly?
Am I just not using the right software to view and then print the document?

Help is greatly appreciated.

**Comment by crowdynasty** [comment]
Follow up:

Just updated the MyCelium wallet with the same result.

**Comment by crowdynasty** [comment]
Also, the wallet used to stop working when I submitted a the passphrase, never before the pin was inputted. Now it crashes when I plug in the Trezor.

**Comment by Giszmo** [comment]
Please report only one problem per issue.

Which version of Mycelium are you using?

**Comment by Giszmo** [comment]
The BIP38 backup restore was broken. The decryption did not start. This is fixed in 3.2.0.17.
