### ISSUE TITLE
Start the transition to Dart/Flutter

### ISSUE THREAD

**Issue by MichelDiz** [mycelium-com/wallet-android#535]
In this coming decade, Google will switch the operating system on its Smartphones. This is the main reason for transitioning to a development platform that will be the main source of new applications for the new Fuchsia OS.

However, migrating to Flutter gains other advantages than being prepared for the future of popular smartphones. Flutter has been consolidating to run everywhere. From Smartphones to Desktops. With the same code in Dart/Flutter.

If you start now, the "rush" to support future buyers of Fuchsia smartphones will have less impact.

Other than that mentioned there are other advantages I would like to list:

- Flutter is getting easier and increasing the user base and open source projects.
- It is possible to implement native functions and APIs easily via Flutter. Instead of waiting too long to implement via JAVA. The same feature would work on all OSs currently supported by Flutter and the future.
- No need to start from scratch for now. Flutter accepts to import the current JAVA code. https://flutter.dev/docs/development/add-to-app
- The project can attract more people to contribute.
- The design would be easier to handle. Today Flutter is already supported by good design editors. Like Adobe XD.
- Why not a Desktop app?

Cheers.

**Comment by Giszmo** [comment]
Thanks but I guess not now.
