### ISSUE TITLE
Option to import key and refresh is missing when MediaFlow disabled

### ISSUE THREAD

**Issue by jbrepogmailcom** [mycelium-com/wallet-android#537]
When I disable MediaFlow in External services settings, the option to import keys disappears and some refresh options do not work. It looks like controls on the top of page are displayed at wrong page and do not work

**Comment by Giszmo** [comment]
We will look into this. Thank you for reporting.

**Comment by Giszmo** [comment]
Issue fixed in ab42e8eec958b88cceca7f07a9bb027a921bdb16 to be available with our ethereum feature release 3.3.x
