### ISSUE TITLE
Add New Account moves from accounts to balance and is not functional anymore when Media Flow is disabled

### ISSUE THREAD

**Issue by MangaKhan** [mycelium-com/wallet-android#538]
**Issue**
"Add New Accounts" button does not work when Media Flow is disabled

**How to reproduce**
1. Check tab "Accounts" and make sure you see the key icon to "Add New Accounts"
2. Go to "Balance" and make sure you do **not** see the key icon to "Add New Accounts" 
3. Go to settings/External Services **turn off Media Flow**
4. Check tab "Accounts": the key icon to "Add New Accounts" **is not available**
5. Check tab "Balance": the key icon to "Add New Accounts" **is available, but not functional**
6. Turn on Media Flow again in order to go back to regular behaviour

**Details**
Version: 3.2.0.17
System: Android 9 on Samsung Galaxy S9+ (SM-G965F)

**Comment by Giszmo** [comment]
This bug is known and I guess it will be fixed in the new feature release, only. We are about to release 3.3.x which should resolve this and other issues.

**Comment by Giszmo** [comment]
3.3 is now rolled out.
