### ISSUE TITLE
no server connected!!!!!! multiple users having same problem

### ISSUE THREAD

**Issue by reddawg7701** [mycelium-com/wallet-android#546]
This seems to be happening to a lot of us, @Giszmo what is going on with the servers? Nothing is working on the app? our bitcoin is just lost in space??

![image](https://user-images.githubusercontent.com/60709607/73972572-e7a7f700-48d5-11ea-864e-04dd4b89b88f.png)

**Comment by Giszmo** [comment]
This is a duplicate of #489
