### ISSUE TITLE
Feb 8, 2020 Update CRASHES

### ISSUE THREAD

**Issue by EAWF** [mycelium-com/wallet-android#547]
Google Playstore update of Feb 8,2020 crashing on my LG Arista running Android 7. Kernel 3.18.31
Ran the other day, now just crashing and quickly auto closing without allowing me to provide feedback.

**Comment by M3zaint** [comment]
I experience the same

**Comment by Metrocreative** [comment]
Same here, y app is currently crashing on startup, app version 3.3.0.17 and android version 10 on a Pixel 3.

**Comment by Chrisg071** [comment]
have same problem on samsung S10 , cant acces my wallets

**Comment by M3zaint** [comment]
Last update fixed my access problems thank god

**Comment by Giszmo** [comment]
The problem was not an update but a server misconfiguration that sent the client into a crash-loop. Please just update from Google Play!
