### ISSUE TITLE
Lost access to 16000usd *SOLVED*

### ISSUE THREAD

**Issue by M3zaint** [mycelium-com/wallet-android#548]
App keeps crashing in midst of move to new phone (unrootable huawei) on android 9 and crashes on app start and I don't know what to do? 
if I loose these coin I'm done. 

Im guessing I should wait a new rls and don't touch the app?

**Comment by nikola68** [comment]
Did you get your issue solved?

**Comment by Hitgub01** [comment]
I ve the same problem

**Comment by M3zaint** [comment]
> Did you get your issue solved?
Yes later pushed update resolved my access. And I'll never use a unrooted phone again (no backups possible of the app itself without root)

**Comment by M3zaint** [comment]
I opened again but u guys really shud start own bug reports also if u have issues, mine is solved

**Comment by nikola68** [comment]
I don't inderstand

**Comment by nikola68** [comment]
How did you get it solved

**Comment by M3zaint** [comment]
I mean I closed the report for comments, and now reopened as u guys hadn't started bugreports I'd let you write here, but I urge you to start own bugreports to make awareness to the team.

**Comment by nikola68** [comment]
Ok, how did you get your issue solved.
If possible it can work for me

**Comment by M3zaint** [comment]
> How did you get it solved

It was solved by the latest update on this repo just like 12hours after it got fucked..

**Comment by nikola68** [comment]
Honestly am really sad,my bp should be up by 40% in the last 5days. I got no reply from neither the team nor gizmo nor mycelium itself

**Comment by M3zaint** [comment]
Tried downloading last version from github as it's nit yet in play store that fixed mine

**Comment by nikola68** [comment]
Can I get a link for that.
But am sure I have the version V3.3.1.1 i think

**Comment by M3zaint** [comment]
Yeah it was infact tgta version fixed mine (I did a cache clear first NOT DATA JUST CACHE) https://github.com/mycelium-com/wallet-android/releases/tag/v3.3.1.1

**Comment by nikola68** [comment]
I hope it fix mine too

Thanks man

**Comment by M3zaint** [comment]
No problem good luck

**Comment by Giszmo** [comment]
The update is not on GitHub but on [our website](https://wallet.mycelium.com/contact.html).
