### ISSUE TITLE
ACCOUNTS status bar runing

### ISSUE THREAD

**Issue by bom64** [mycelium-com/wallet-android#559]
For me all status bar is running for all keys lines. They run up to 5 minute.
Status bar is a small blue line that is running from left to right.

Is the servers working?

**Comment by Giszmo** [comment]
Is this still occurring? Syncing can take occasionally longer as the wallet syncs all addresses rather than only the current receive address which is quicker. Or do you think it's a UI issue?

**Comment by bom64** [comment]
No, not more.
