### ISSUE TITLE
Recovered wallet from a client

### ISSUE THREAD

**Issue by ghost** [mycelium-com/wallet-android#561]
A client which uses mycellium accidentally erased the app.
He asked for my recovery services with the mnemonic phrase.
After searching, their funds were there, but the account seed #2 (m/44'/0'/2')
The app doesn't let you create news account if you haven't movements on previous account, so how he created account #2 without #0 and #1?
Obviously he wasn't available to access to their wallet after restore it and when I tried neither, I had to use other tools.

**Comment by ogarralda** [comment]
Marcelo, soy Oscar Garralda el que le recuperaste por este comentario, en realidad yo no hice lo que alli pusiste pero me gustaría me lo explicaras mejor.
No obstante tengo ora persona que le pasó algo parecido, le transfirienron y luego le desapareció, actualizó la versión, escribió a Mycelium y nunca le contestaron.  Los fondos existen y se ve en el buscador. Entiendo que podrías hacer lo mismo?

**Comment by mrbianchi** [comment]
> 
> 
> Marcelo, soy Oscar Garralda el que le recuperaste por este comentario, en realidad yo no hice lo que alli pusiste pero me gustaría me lo explicaras mejor.
> No obstante tengo ora persona que le pasó algo parecido, le transfirienron y luego le desapareció, actualizó la versión, escribió a Mycelium y nunca le contestaron. Los fondos existen y se ve en el buscador. Entiendo que podrías hacer lo mismo?

contactame por facebook fb.me/0marce

**Comment by Giszmo** [comment]
Regarding OP's issue ... OP has no github account anymore and for all we know the original wallet might have been created by other software and only was imported to Mycelium later.
