### ISSUE TITLE
Does Mycelium support importing BIP39 keys (12 words)? Only that.

### ISSUE THREAD

**Issue by bitcoinmeetups** [mycelium-com/wallet-android#562]
Does Mycelium support importing BIP39 keys (12 words)? Only that.

**Comment by zentown** [comment]
no, it support importing at least 24 BIP39 Mnemonic words + optional BIP39 Passphrase for generating the seed

**Comment by Giszmo** [comment]
![Screenshot from 2020-10-13 00-55-30](https://user-images.githubusercontent.com/96378/95813697-d75edc00-0cee-11eb-8da0-47c95a8ea8e8.png)

It supports 12, 18 and 24 words, with or without passphrase, english only. That's BIP39.
It finds BIP44, BIP49 and BIP84 accounts.

It strictly uses the BIP32 GAP limit of 20, so non-standard wallets (BTCPayServer for example) will not be recovered in all cases.
