### ISSUE TITLE
Mycelium ETH wallet NEGATIVE BAL. ⚠ 

### ISSUE THREAD

**Issue by Bitcoinlordofficial** [mycelium-com/wallet-android#563]
Hello, i had tried reloading my ETH wallet from the account tab section as recommended, but it is still showing a negative balance meanwhile the ETH blockchain has confirmed fund in my account. 

Dear Mycelium, 

This does not make sense for your esteemed. 

Support not responding. My regrets thooo

However, who can help??

**Comment by CHAPEROVA** [comment]
My coins disappeared since March they were intermittent, in April they disappeared and my balance was negative.
I have followed the instructions and they do not appear, but the consignments of my smart contract are registered.

**Comment by Giszmo** [comment]
This bug is fixed since long
