### ISSUE TITLE
Rate fiat problem MyCelium API server

### ISSUE THREAD

**Issue by Sulvus** [mycelium-com/wallet-android#564]
Mycelium WAPI Server seems always is returning modified values compared with real source.
I attach screenshot example. Its not a delay, price shows always lower in all source providers.
https://imgur.com/a/oI0qLtP

**Comment by Sulvus** [comment]
Is not a problem of client. The rates come from https://mws30.mycelium.com/wapitestnet/wapi/getExchangeRates API json

**Comment by Giszmo** [comment]
"The exchange rate" is not actually a thing. Exchanges report:

* moving average
* last trade
* best sell price
* best buy price

We often use the average of the best buy and best sell price while other sources might present the last trade or even the moving average. At times those can diverge.

As for your screenshots, in the case of Kraken, we use [this API call](https://api.kraken.com/0/public/Ticker?pair=XXBTZUSD").

That reply is a bit cryptic. Our code uses the first child from the "c" value which according to the [api documentation](https://www.kraken.com/features/api#get-ticker-info) is the last trade's price. That looks good to me.

**Comment by Sulvus** [comment]
Hello,
I investigated a bit and the exchange rate only is good in USD.
I think when you choose EUR for and Kraken exchange for example. It checks XBTUSD and after do a EURUSD conversion on other place. The correct way is check XBTEUR directly.

This cause me a lot discusions with other people who use mycelium too about the real amount when I receive/send.

I attach screenshot. Real XBTEUR in Kraken and mycelium rate. https://i.imgur.com/LCtEn1c.png

**Comment by Giszmo** [comment]
Your observation is correct. If that is unacceptable, I suggest to open a new issue suggesting/requesting a feature that makes sure that exchange rates are not computed the way they currently are.
