### ISSUE TITLE
One of the root or intermediate certificates has expired (12 days ago).

### ISSUE THREAD

**Issue by idnit88** [mycelium-com/wallet-android#565]
```Common name: *.mycelium.com
SANs: *.mycelium.com, mycelium.com
Valid from May 13, 2019 to May 13, 2021
Serial Number: 54e176288a9cfd8d8bdf6a801375cf75
Signature Algorithm: sha256WithRSAEncryption
Issuer: Sectigo RSA Domain Validation Secure Server CA 
```

```
Common name: USERTrust RSA Certification Authority
Organization: The USERTRUST Network
Location: Jersey City, New Jersey, US
Valid from May 30, 2000 to May 30, 2020
Serial Number: 13ea28705bf4eced0c36630980614336
Signature Algorithm: sha384WithRSAEncryption
Issuer: AddTrust External CA Root
```
Is this why I am getting no server connection ?

Android 5

**Comment by idnit** [comment]
Happening to me as well, getting no server connection error on older Android device.

**Comment by idnit88** [comment]
```
2020-06-04 10:06:54.471:INFO:Connection to electrumx-1a0.mycelium.com:10000 closed
2020-06-04 10:06:56.914:INFO:Connecting to electrumx-2a1.mycelium.com:10000
2020-06-04 10:06:58.725:INFO:Connection thread loop interrupted. Reason: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Sat May 30 05:48:38 CDT 2020 (compared to Thu Jun 04 22:06:58 CDT 2020)
```

Not positively sure this is the problem but I need a little help here..

Getting no server connection error , can't create a backup phrase because new PIN has to have 200 blocks before allowing a new backup phrase. Coin locked in new account created since last backup was created...

How to get keys from wallet when it can't connect to the node ?

**Comment by Giszmo** [comment]
> How to get keys from wallet when it can't connect to the node ?

The xpriv export does not care about the "200 blocks" part.

I'm pretty sure the certificate issues are resolved since long. Closing.
