### ISSUE TITLE
Link to block explorer is munged

### ISSUE THREAD

**Issue by phptek** [mycelium-com/wallet-android#573]
Version: 3.5.4.2
O/S: Android 9

Select a transaction > show details > select inputs (or outputs) > error:

blockchainbdgpzk.onion’s server IP address could not be found

I'm using Orbot and the service is running. Disabling Tor and the feature of course works A-OK.

Is the use of Tor to achieve this strictly necessary? I guess I had assumed that all Tor was used for was to route transaction traffic, not ordinary web traffic.

**Comment by Giszmo** [comment]
The TOR integration is currently very neglected and I suggest you do not swith Mycelium to use TOR but to configure Orbot to proxy Mycelium through TOR.

That said, the original idea was probably that if you require additional privacy when syncing your wallet, you probably don't want to spoil it all when checking a block explorer.
