### ISSUE TITLE
ads :(

### ISSUE THREAD

**Issue by lzunsec** [mycelium-com/wallet-android#578]
I miss the old mycelium. Just downloaded after some years and got casino ads on my phone. This doesn't look good, specially for bitcoin. Bitcoin does not combine with casino ads, looks like scam. Make a paid version, or fund it somehow.

PS: deterministic building is great

**Comment by Giszmo** [comment]
I'm all with you but there is no provider who could prove so far that the paid model would work, too, so I kind of understand the management's position to go with ads, too. Ads are just ads and don't affect the wallet's security. Your concern was heard but this issue as such will not get fixed.
