### ISSUE TITLE
Exchange of eth for btc incomplet

### ISSUE THREAD

**Issue by Ameyaw1** [mycelium-com/wallet-android#580]
I attempted to exchange eth for btc within mycelium wallet. Eth was sent and confirmed but no btc received after 72 hours.

9d30ce9230a4b9fcda1bf55a7a8e68b89d9c33a0952de7ac91865c1e1ddf176a

**Comment by MudWar** [comment]
What about now?

**Comment by Ameyaw1** [comment]
Still zero response from mycelum support. Funds remain outstanding

**Comment by Gitwilhub** [comment]
Wait please

**Comment by Gitwilhub** [comment]
Mycelium not received Eth-20
Received only btc how much you send you will have fee if you can cancel do
it and wait 30 minutes I check it out

Le ven. 8 janv. 2021 8:04 p.m., Jeejee Wilson <jeewils92@gmail.com> a
écrit :

**Comment by Ameyaw1** [comment]
The eth was sent and confirmed 
Cannot cancel
Still no btc received 
Still no acknowledgement from support@mycelium.com

**Comment by Giszmo** [comment]
This issue is stale and should be resolved by support, not here. Closing.

**Comment by Ameyaw1** [comment]
This issue was never acknowledged or addressed by support
So fuck u

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Giszmo** [comment]
I see it was 15ETH? Did anybody reply at all or was the transaction not recognized as belonging to the exchange feature?

**Comment by Ameyaw1** [comment]
No reply. Now it's almost 4 months
The eth was sent in the wallet exchange feature.
Who gets that money if I don't get it back?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Giszmo** [comment]
That feature is provided by [Changelly](https://github.com/mycelium-com/wallet-android/blob/master/mbw/src/main/java/com/mycelium/wallet/external/changelly/ChangellyAPIService.java#L85) but I think Mycelium sells it white-label, so Mycelium should be the organization to talk to. If I were you, I would probably talk to both.

**Comment by Ameyaw1** [comment]
Mycelium is not responding.
Changely also ignores me.
But thank you.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Ameyaw1** [comment]
Thanks for your advice. Mycelium never responded but changely did and I got my.momey back!
Super 🙏🏾grateful

Sent from ProtonMail mobile

-------- Original Message --------
