### ISSUE TITLE
Keys used more than once? Wallet shows old Bitcoin transactions but also Eth transactions from someone else.

### ISSUE THREAD

**Issue by diggggst** [mycelium-com/wallet-android#585]
Hi, I contacted support already, but no answer yet.

In 2016 I used Mycelium on Android for a couple of Bitcoin transactions. Backed up my seed phrase. A few days ago I restored this seed in the current Mycelium wallet (I had it installed all the time actually, but updated it in the meantime, and wanted to check a few old seed phrases to export transactions). Now I switched to the Ethereum part of the wallet, which I have never used with this wallet. I was surprised to see a couple of Ether transactions that someone else must have performed. The amounts, addresses, transaction pattern and so on were all not mine. They all happened within 10 days in 2016, when Ethereum was not yet implemented. 5 tx went in from Kraken, then the money left the wallet 10 days later.

I just wanted to let you know this, in case there is buggy code, and in case other wallet manufacturers use the same code (which I hear happens).

I could share everything, including the seed phrase, if needed.
[edit] This should not matter much, but there is a possibility that I have created the seed with a different wallet. But I'm pretty sure it was this one.

**Comment by Giszmo** [comment]
That sounds definitely strange. Thanks for reporting.

So you see ETH transactions from 2016? Do you have transaction IDs? Do those "ETH" transactions correlate to any BTC transactions? When you say Kraken, how do you know it's Kraken? What version of Mycelium are you using?

**Comment by diggggst** [comment]
Hi, thanks, but I think this has been indeed a user error...

**Comment by Giszmo** [comment]
So ... I close the issue? I read your comment as such. Let me know if I understood you wrong.

**Comment by diggggst** [comment]
Yes, closing was right, thank you. My bad.
