### ISSUE TITLE
Cant remember 12 word to login on new device 

### ISSUE THREAD

**Issue by MaverickIX** [mycelium-com/wallet-android#589]
Good day . My old Samsung phone was not working anymore so I got a new phone and downloaded the mycelium app on the new phone . I wrote down the 12 words to login in to my account in a book but cant find it . I can not get into my account. Someone please help me !!!!

**Comment by tgbv** [comment]
Account keys are derived from those 12 words written in that exact order. Unfortunately no one can help you restore your account.

**Comment by Giszmo** [comment]
Unfortunately tgbv is right. If you already disposed of the old phone and the book, there is no way of getting those Bitcoins back. They are lost forever.
