### ISSUE TITLE
Mycelium wallet error message EIP-155

### ISSUE THREAD

**Issue by nesacable** [mycelium-com/wallet-android#591]
Since 17.3.2021 u i have issue with Mycelium wallet , i can not send out ETH coins
 I got this error message  every time when i try it   **Only replay-protected (EIP-155) transaction allowed over RPC** 

I have 7 ETH in Mycelium wallet that i can not send to nobody 

No email back from support@mycelium.com since 18.3.2021 

Does anybody had similar situation ?

I really belief that Mycelium support will answer and fix this issue.

Thank you in advance 

![viber_image_2021-03-19_18-18-11](https://user-images.githubusercontent.com/81088301/111905867-2ce1a680-8a4e-11eb-8ba2-073bdea49cf3.jpg)
![viber_image_2021-03-21_14-01-58](https://user-images.githubusercontent.com/81088301/111905868-2e12d380-8a4e-11eb-953a-a28a144c556b.jpg)

**Comment by tgbv** [comment]
I think it's Mycelium bug: 

https://ethereum.stackexchange.com/questions/94412/valueerror-code-32000-message-only-replay-protected-eip-155-transac

**Comment by Maxsurf** [comment]
I also have same issue for past 24 hours. Emailed support.
Looked at every possible setting within the app. Restarted phone. There was an issue with Samsung devices and recent update. May I ask which device you are using?

**Comment by Maxsurf** [comment]
I have 5 different ethereum wallets within the app and for some reason when I backup wallet #4, the app gives me seed from the main wallet #1 and when I try to restore by using another app I obviously can only import wallet #1. I think it may also be a bug. I'm stuck with the EIP155 error and also unable to export my wallet to another app.

**Comment by Dd0305** [comment]
if there are no capital letters in the destination address, could this be the problem?

**Comment by nesacable** [comment]
Hello Guys , i transfer the money try Exodus app . 
download Exodus wallet  and use 12 words from your Mycelium app , all balance will synchronize and transfer to Exodus wallet . 

This is the only way for now

**Comment by Kogut55** [comment]
Hi i do recovery in too exodus wallet but saldo its 0, in my mycelium i have some PAX coin and some ETH,, its this method should worki also for other Erc20 coins? What i do wrong, i have 3 ETH acounts in mycelium app....  Please help me

**Comment by Giszmo** [comment]
The latest version 3.8.9.0, available on our website and on Google Play fixes this issue.

**Comment by Kogut55** [comment]
Unfortunately the update does not fix the error, ETH can now be sent.  I still can't send ERC20 tokens, I have PAXi ETH tokens on my wallet, if I want to send PAX, there is still the same EIP155 error, THE UPDATE HAS NOT FIXED THE PROBLEM, THE TOKENS ARE BLOCKED, NO POSSIBILITY TO TRANSFER, EVEN IN INTERNAL ACCOUNTS

**Comment by Giszmo** [comment]
Thank you @Kogut55. We will look into it.

**Comment by Giszmo** [comment]
On [our website](https://wallet.mycelium.com/) you can find the upcoming bugfix release v3.8.9.1. The link has some old version label but the binary is the latest.

Generally if you have an Android app installed, you can only install updates that are signed by the same provider and that do not decrement the version, so if you are hesitant to upgrade from a website, research this security feature of the Android OS. Or wait some days until the app is through the Google verification.

**Comment by Kogut55** [comment]
Yes, this update has fixed the problem, thank you very much for the information.
