### ISSUE TITLE
Transaction not confirm

### ISSUE THREAD

**Issue by Bobshinery** [mycelium-com/wallet-android#596]
Hello
I've been trying to send Bitcoin since 2days now and the transaction is yet to confirm.

I tried using another wallet and it working which means, it only on mycelium.

Please help me rectify this.

**Comment by Giszmo** [comment]
Mycelium allows you to pick arbitrarily low fees and if you do so, you might get transactions that do not confirm ever. To remedy this, select the transaction and from the context menu bump it with CPFP.
