### ISSUE TITLE
Use /bin/sh instead of /bin/bash when possible

### ISSUE THREAD

**Issue by emanuelb** [mycelium-com/wallet-android#597]
There are scripts in this repo that are using `#!/bin/bash`, for some of them it's possible to use `#!/bin/sh` instead without other modifications:

`./trezor/build_pb.sh` https://github.com/mycelium-com/wallet-android/blob/1f434c409d9f4dba4e173b6a800bba56dfa63fd8/trezor/build_pb.sh
`./mbw/res-sources/updateDrawables.sh` https://github.com/mycelium-com/wallet-android/blob/1f434c409d9f4dba4e173b6a800bba56dfa63fd8/mbw/res-sources/updateDrawables.sh
`./checkBuild.sh` https://github.com/mycelium-com/wallet-android/blob/02bd26f4152999a647fbb40a59da7d51358bc831/checkBuild.sh

Use `#!/bin/sh` instead of  `#!/bin/bash` when possible, also it might worth to change it for some other scripts if they not relaying to much on bash specific operations (see checkbashisms tool: https://manpages.debian.org/unstable/devscripts/checkbashisms.1.en.html)

**Comment by Giszmo** [comment]
I guess this is not worth the edit. Many of those scripts are stale anyway and more a reminder how to do things than stuff we use on a daily basis. But thanks for the heads-up.
