### ISSUE TITLE
Broken link to direct APK download in README

### ISSUE THREAD

**Issue by emanuelb** [mycelium-com/wallet-android#598]
in README file: https://github.com/mycelium-com/wallet-android/blob/76407f08933d098a51a7648162d6894316bc6f02/README.md#build-commands

From: 
> you can obtain the apk directly from the Mycelium Bitcoin Wallet download page.

The "download page" Link is to: https://wallet.mycelium.com/contact.html which return 404 not found error, it's also better to use custom 404 page instead of nginx default one.

**Comment by Giszmo** [comment]
Thanks. We are aware of this and the person in charge will fix it soon.
