### ISSUE TITLE
Building instructions contain old versions

### ISSUE THREAD

**Issue by emanuelb** [mycelium-com/wallet-android#599]
in README file: https://github.com/mycelium-com/wallet-android/blob/76407f08933d098a51a7648162d6894316bc6f02/README.md#building

> The project layout is designed to be used with a recent version of Android Studio (currently 1.1.0)

while the latest version of android studio is: 4.1.3 and beta is 4.2

- JDK 1.7

The LTS versions of JDK are 8 & 11.

Also old versions of below tools:

> Android SDK Tools 22.6.4
SDK Platform Tools 19.0.2
Android SDK build Tools 19.1.0
Android 4.4.2 (API 19) (at least SDK Platform Rev. 3)
Android Support Repository rev 5
Android Support Library rev 19.1
Google Play services for Froyo rev 12
Google Play services rev 17
Google Repository rev 8

not sure if such old tools can even be used to build the latest commit, either way replace the versions with recent ones, and ensure it's list only required deps in order to compile the app.

**Comment by Giszmo** [comment]
This will be fixed soonish. PR in internal repo.
