### ISSUE TITLE
Website shows older version for google-play & direct download

### ISSUE THREAD

**Issue by emanuelb** [mycelium-com/wallet-android#601]
Visiting:
https://wallet.mycelium.com/

Shows version 3.8.6.1:

> Direct Download
(APK, v. 3.8.6.1)
Download from Google
(v. 3.8.6.1)

while the latest version is: 3.8.9.0 as can be seen from: https://play.google.com/store/apps/details?id=com.mycelium.wallet

> Current Version
3.8.9.0

**Comment by Giszmo** [comment]
Thanks. We are aware of this and the website maintainer should fix it soon. The [old download link](https://wallet.mycelium.com/contact.html) is also broken.
