### ISSUE TITLE
App crash: Transaction change handling selection

### ISSUE THREAD

**Issue by JijoBose** [mycelium-com/wallet-android#624]
Selecting any option from "Transaction change handling" causes the app to crash

**Comment by agneslovelace** [comment]
Thank you for bringing it to our attention. We will release the bugfix right away.

**Comment by JijoBose** [comment]
Closing this issue cause, it is fixed in the version [v3.11.0.10](https://github.com/mycelium-com/wallet-android/releases/tag/v3.11.0.10)
