### ISSUE TITLE
Bitcoin Cash redeption

### ISSUE THREAD

**Issue by gjmulder** [mycelium-com/wallet-android#630]
I received some BTC into my Mycelium wallet before the BCH fork.

With the lack of BCH support in Mycelium I had assumed I could simply enter my 12 word master seed into Coinomi, add BCH with the derivation path M/44H/0H/0H and my BCH should show on rescan.

However, when I look on a BCH block explorer I can see that subsequent transactions I did in Mycelium on the BTC blockchain seem to also be present on the BCH blockchain. My understanding was that there was replay protection on the BCH blockchain to prevent this?

I now have no idea which BTC privkey in Mycelium was used to receive the BCH transaction.

**Comment by souzagroup** [comment]
Yea, me too. It is not clear.. I read Coinomi is the only platform that can help, however, it isnt clear
