### ISSUE TITLE
Users' only option seems to be to pester employees regarding downtime and/or exchange source problems.

### ISSUE THREAD

**Issue by dscotese** [mycelium-com/wallet-android#640]
I believe the connection between Kraken and Mycelium servers is down and there is no way for me to ensure that the team knows about it, or to see if they already know about it and are working on it.

Feature Request: Add a "Notice Box" to mycelium.com that shows the latest important thing the team wants users to know.  If you have a list of items that describe the most common things users would want to pester you about, add checkboxes below the notice box for users to submit.

If you're having trouble, please let everyone know.  We have enough money to support your needs and would love to know more about what they are if the company is having any financial trouble.

**Comment by JayZee1210** [comment]
support@mycelium.com  i emailed  about  wallet not updating  its showing the same  value for past  24  hours

**Comment by dscotese** [comment]
Problem has been fixed.
