### ISSUE TITLE
Not updating 

### ISSUE THREAD

**Issue by JayZee1210** [mycelium-com/wallet-android#641]
Mycelium wallet not updating showing lower price of Bitcoin than it actually is , and allowing me to make purchases at that price

**Comment by DfrostX** [comment]
Same here. price has not updated in 12hrs

**Comment by dscotese** [comment]
This sounds like a problem I saw about three weeks ago.  The problem has gone away.  Is it still an issue for you, @JayZee1210 ?  If not, can you close this?

**Comment by JayZee1210** [comment]
Fixed thank you
