### ISSUE TITLE
3.16.0.13 is not reproducible

### ISSUE THREAD

**Issue by Giszmo** [mycelium-com/wallet-android#648]
Apparently some data binding doesn't work deterministically. I failed to reproduce the latest binary. My full analysis and diffoscope output is [here](https://walletscrutiny.com/android/com.mycelium.wallet/).

**Comment by AlexanderPavlenko** [comment]
Hi, Leo! Thanks for reporting this. Please check [v3.16.0.15](https://github.com/mycelium-com/wallet-android/releases/tag/v3.16.0.15), it should be reproducible! There's also SHA512 in the release tags to verify the downloaded APKs authenticity.

**Comment by Giszmo** [comment]
https://walletscrutiny.com/android/com.mycelium.wallet/
