### ISSUE TITLE
Show offline, but active, addresses as payment source

### ISSUE THREAD

**Issue by WACOMalt** [mycelium-com/wallet-android#83]
When I click a Bitcoin link (or scan via NFC) I'd like it to show all active keys, even cold storage ones. If a cold storage address is picked, it should bring up the window to scan the private key. 

I keep a paper backup card (BIP38 encrypted) in my wallet, but to use it I have to manually choose a cold storage transaction from the main screen. Should be able to initiate that via link. Would also be nice to still show the send button when using cold storage addresses, and bring up the private key obtain screen when clicked.

**Comment by Giszmo** [comment]
With a BIP38 QR/NFC what you would usually do is scan that one first, then click spend, then scan the target. I think that is easy enough a work flow.
